import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, Cable, Camera, CheckCircle2, CircleDot, KeyRound, MessageCircle, Network, Radio, Router, ShieldCheck, Siren, Wrench, Wifi } from "lucide-react";
import { localizedPath, localizedUrl } from "@/lib/technicalRoutes";
import { technicalWhatsAppHref } from "@/lib/technicalWhatsApp";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params; const es = locale === "es"; const path = "services/security-networks"; const canonical = localizedUrl(locale, path);
  return { title: es ? "CCTV, Redes, Fibra y Control de Acceso en Valencia | THEVULGO" : "Security, CCTV, Networks & Fiber in Valencia | THEVULGO", description: es ? "División técnica para CCTV, WiFi, redes, fibra, cableado, control de acceso, videoporteros y sistemas de negocio en Valencia." : "Technical division for CCTV, WiFi, networks, fiber, cabling, access control, intercom and business systems in Valencia.", alternates: { canonical, languages: { en: localizedUrl("en", path), es: localizedUrl("es", path), "x-default": localizedUrl("en", path) } }, openGraph: { title: es ? "CCTV, Redes, Fibra y Control de Acceso" : "Security, CCTV, Networks & Fiber", description: es ? "Instalaciones técnicas para viviendas y negocios en Valencia." : "Technical installations for Valencia homes and businesses.", url: canonical, type: "website", siteName: "THEVULGO" } };
}

const categories = [
  ["cctv", "CCTV & Video Surveillance", "CCTV y Videovigilancia", "Cameras, NVR/DVR, PoE, storage, remote viewing and system upgrades.", "Cámaras, NVR/DVR, PoE, almacenamiento, acceso remoto y mejoras.", Camera, ["IP / PoE", "NVR / DVR", "Remote view"]],
  ["redes", "WiFi & Networks", "WiFi y Redes", "Access points, LAN, Ethernet, VLAN, routers, switches and managed networks.", "Puntos WiFi, LAN, Ethernet, VLAN, routers, switches y redes gestionadas.", Network, ["WiFi", "LAN", "VLAN"]],
  ["fiber", "Fiber Optic", "Fibra Óptica", "Fiber runs, termination, splicing, diagnosis, rack and backbone integration.", "Tendidos, terminación, fusión, diagnóstico e integración en rack y backbone.", Cable, ["LC / SC", "SFP", "Backbone"]],
  ["redes", "Structured Cabling", "Cableado Estructurado", "Cat6/Cat6A network points, patch panels, racks, labelling and testing.", "Puntos Cat6/Cat6A, patch panels, racks, etiquetado y pruebas.", Router, ["Cat6", "Cat6A", "RJ45"]],
  ["control-de-acceso", "Access Control", "Control de Acceso", "Readers, keypads, controllers, electric strikes, magnetic locks and staff access.", "Lectores, teclados, controladores, cerraderos, electroimanes y acceso de personal.", KeyRound, ["RFID", "Keypad", "Locks"]],
  ["intercom", "Intercom & Door Entry", "Videoporteros y Entrada", "Video intercom, IP intercom, gate release, indoor monitors and mobile apps.", "Videoportero, sistemas IP, apertura de portón, monitores y apps.", Radio, ["Video", "IP", "Gate"]],
  ["alarmas", "Standalone Alarm Systems", "Alarmas Autónomas", "Panels, sensors, sirens, keypads, app notifications, repair and upgrades.", "Centrales, sensores, sirenas, teclados, avisos por app, reparación y mejoras.", Siren, ["Sensors", "Sirens", "App"]],
  ["seguridad-comercial", "Business Security Infrastructure", "Infraestructura Técnica para Negocios", "Combined CCTV, networks, access, fiber, racks, WiFi and cabling projects.", "Proyectos conjuntos de CCTV, red, acceso, fibra, racks, WiFi y cableado.", Building2, ["CCTV", "Network", "Access"]],
  ["starlink", "Starlink & Outdoor Connectivity", "Starlink y Conectividad Exterior", "Satellite internet setup, outdoor links and backup connectivity where appropriate.", "Instalación de internet satélite, enlaces exteriores y conectividad de respaldo.", Wifi, ["Starlink", "Outdoor", "Backup"]],
  ["redes/network-diagnostics-valencia", "Diagnostics & Existing-System Repair", "Diagnóstico y Reparación", "Find faults, repair, clean up, reconfigure or expand existing technical systems.", "Localización de fallos, reparación, orden, reconfiguración o ampliación.", Wrench, ["Diagnose", "Repair", "Upgrade"]],
] as const;

export default async function Page({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const es = locale === "es";
  const estimate = `${localizedPath(locale, "estimate")}?category=commercial`;
  return <main className="bg-white text-neutral-950">
    <section className="relative overflow-hidden bg-neutral-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(250,204,21,.18),transparent_35%)]" /><div className="relative mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="inline-flex items-center gap-2 rounded-full border border-yellow-400/50 bg-yellow-400/10 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-yellow-400"><ShieldCheck className="h-4 w-4" />THEVULGO SECURITY & NETWORKS</div><h1 className="mt-7 max-w-5xl text-4xl font-black leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">{es ? "CCTV, Redes, Fibra y Control de Acceso en Valencia" : "Security, CCTV, Networks & Fiber in Valencia"}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-neutral-300">{es ? "Un único equipo técnico para CCTV, redes, fibra, accesos e infraestructura conectada en viviendas y negocios." : "One technical team for CCTV, networks, fiber, access and connected infrastructure for homes and businesses."}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={estimate} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-yellow-400 px-6 py-4 font-black text-black">{es ? "Configurar presupuesto" : "Build your project estimate"}<ArrowRight className="h-5 w-5" /></Link><a href={technicalWhatsAppHref("commercial", locale)} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl border border-neutral-600 bg-neutral-900 px-6 py-4 font-black"><MessageCircle className="h-5 w-5 text-yellow-400" />{es ? "WhatsApp con un técnico" : "WhatsApp a technician"}</a></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm text-neutral-300">{(es ? ["Viviendas y negocios", "Valencia y alrededores", "Español / Inglés", "Mejoras de sistemas existentes", "Instalaciones nuevas"] : ["Homes & businesses", "Valencia & nearby", "English / Spanish", "Existing-system upgrades", "New installations"]).map((item) => <span key={item} className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-yellow-400" />{item}</span>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[.16em] text-yellow-600">{es ? "División técnica" : "Technical division"}</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">{es ? "Desde una avería hasta un proyecto completo" : "From one fault to a complete project"}</h2><p className="mt-5 text-lg leading-8 text-neutral-600">{es ? "Diagnosticamos, reparamos, ampliamos e instalamos sistemas. No todo requiere sustituirlo todo." : "We diagnose, repair, expand and install systems. Not every project needs a complete replacement."}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{categories.map(([href, en, esTitle, enDesc, esDesc, Icon, tags]) => <Link key={en} href={localizedPath(locale, `services/${href}`)} className="group flex min-h-80 flex-col rounded-3xl border border-neutral-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-yellow-400 hover:shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-neutral-950 text-yellow-400"><Icon className="h-6 w-6" /></div><h3 className="mt-6 text-2xl font-black">{es ? esTitle : en}</h3><p className="mt-3 flex-1 leading-7 text-neutral-600">{es ? esDesc : enDesc}</p><div className="mt-5 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag} className="rounded-full bg-neutral-100 px-3 py-1 text-xs font-bold text-neutral-600">{tag}</span>)}</div><span className="mt-6 inline-flex items-center gap-2 font-black">{es ? "Ver soluciones" : "Explore solutions"}<ArrowRight className="h-5 w-5 transition group-hover:translate-x-1" /></span></Link>)}</div></section>

    <section className="border-y border-neutral-200 bg-neutral-50"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-16 md:px-8 lg:grid-cols-2"><div className="rounded-3xl bg-white p-8 shadow-sm"><CircleDot className="h-8 w-8 text-yellow-500" /><h2 className="mt-5 text-3xl font-black">{es ? "Soluciones para viviendas" : "Solutions for home"}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{(es ? ["WiFi para pisos y chalets", "Cámaras y portón", "Videoportero", "Puntos Ethernet", "WiFi Mesh", "Acceso inteligente"] : ["Apartment and villa WiFi", "Home and gate cameras", "Video intercom", "Ethernet points", "Mesh WiFi", "Smart door access"]).map((item) => <div key={item} className="flex gap-2 rounded-xl bg-neutral-50 p-3 text-sm font-bold"><CheckCircle2 className="h-5 w-5 shrink-0 text-yellow-500" />{item}</div>)}</div></div><div className="rounded-3xl bg-neutral-950 p-8 text-white shadow-sm"><Building2 className="h-8 w-8 text-yellow-400" /><h2 className="mt-5 text-3xl font-black">{es ? "Soluciones para negocios" : "Solutions for business"}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{(es ? ["Oficinas y coworking", "Tiendas y retail", "Restaurantes y bares", "Gimnasios y clínicas", "Almacenes", "Hoteles y salones"] : ["Offices and coworking", "Shops and retail", "Restaurants and bars", "Gyms and clinics", "Warehouses", "Hotels and salons"]).map((item) => <div key={item} className="flex gap-2 rounded-xl bg-neutral-900 p-3 text-sm font-bold"><CheckCircle2 className="h-5 w-5 shrink-0 text-yellow-400" />{item}</div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8"><p className="text-sm font-black uppercase tracking-[.16em] text-yellow-600">{es ? "Configuraciones de ejemplo" : "Example configurations"}</p><h2 className="mt-3 text-3xl font-black">{es ? "Estructuras habituales de proyecto" : "Common project structures"}</h2><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[
      [es ? "Red para oficina pequeña" : "Small Office Network", ["Router", "Managed switch", "APs", "Guest network", "Ethernet", "Rack"]],
      [es ? "CCTV para tienda" : "Shop CCTV", ["IP cameras", "PoE", "NVR", "Storage", "Remote view", "Cabling"]],
      [es ? "Acceso de negocio" : "Business Access", ["Reader / keypad", "Controller", "Lock", "Exit button", "PSU", "Users"]],
      [es ? "Infraestructura completa" : "Complete Infrastructure", ["Structured cabling", "WiFi", "CCTV", "Access", "Rack", "Fiber"]],
    ].map(([title, items]) => <article key={title as string} className="rounded-2xl border border-neutral-200 p-6"><h3 className="text-xl font-black">{title}</h3><ul className="mt-5 space-y-2 text-sm text-neutral-600">{(items as string[]).map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-yellow-500" />{item}</li>)}</ul><Link href={estimate} className="mt-6 inline-flex items-center gap-2 font-black underline decoration-yellow-400 underline-offset-4">{es ? "Configurar proyecto" : "Configure project"}<ArrowRight className="h-4 w-4" /></Link></article>)}</div></section>

    <section className="bg-yellow-400"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-14 md:px-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-black">{es ? "Un alcance técnico claro antes de instalar" : "A clear technical scope before installation"}</h2><p className="mt-2 max-w-2xl text-lg">{es ? "Separamos mano de obra, materiales y equipos. Los proyectos complejos pasan por revisión, no por precios inventados." : "We separate labour, materials and equipment. Complex projects receive a review, not an invented price."}</p></div><Link href={estimate} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-black px-6 py-4 font-black text-white">{es ? "Solicitar revisión del proyecto" : "Request project review"}<ArrowRight className="h-5 w-5" /></Link></div></section>
  </main>;
}
