import Link from "next/link";
import { ArrowRight, Cable, CheckCircle2, MessageCircle, Radio } from "lucide-react";
import { getTechnicalLeaves, TECHNICAL_CATEGORY_LABELS, technicalLeafPath, type TechnicalCategoryId } from "@/lib/securityNetworkCatalog";
import { localizedPath, localizedUrl } from "@/lib/technicalRoutes";
import { technicalWhatsAppHref } from "@/lib/technicalWhatsApp";

export default function TechnicalCategoryHub({ category, locale }: { category: TechnicalCategoryId; locale: string }) {
  const language = locale === "es" ? "es" : "en";
  const isEs = language === "es";
  const items = getTechnicalLeaves(category);
  const Icon = category === "fiber" ? Cable : Radio;
  const title = TECHNICAL_CATEGORY_LABELS[category][language];
  const pillar = category === "fiber" ? {
    problems: isEs ? ["Enlaces caídos o inestables", "Conectores o latiguillos dañados", "Necesidad de unir racks, plantas o edificios"] : ["Failed or unstable links", "Damaged connectors or patch leads", "A need to connect racks, floors or buildings"],
    uses: isEs ? ["Backbone de oficina o almacén", "Enlaces entre salas técnicas", "Distribución en rack y patch panel", "Ampliación de infraestructura existente"] : ["Office or warehouse backbone", "Links between equipment rooms", "Rack and patch-panel distribution", "Existing infrastructure expansion"],
    process: isEs ? ["Revisamos extremos, recorrido y equipos", "Confirmamos tipo de fibra y conectores", "Definimos terminación, fusión o reparación", "Comprobamos el enlace y documentamos el resultado"] : ["Review endpoints, route and equipment", "Confirm fiber type and connectors", "Define termination, splicing or repair", "Check the link and document the result"],
    faq: isEs ? [["¿Trabajáis con monomodo y multimodo?", "Sí, tras confirmar el tipo de fibra, conectores y ópticas de ambos extremos."], ["¿Hacéis pruebas OTDR?", "La prueba avanzada se confirma según el proyecto y equipo necesario; no se promete sin revisar el alcance."], ["¿El material está incluido?", "Separamos mano de obra, latiguillos, paneles, conectores y módulos para evitar costes ocultos."]] : [["Do you work with single-mode and multimode?", "Yes, after confirming fiber type, connectors and optics at both ends."], ["Do you provide OTDR testing?", "Advanced testing is confirmed according to project scope and required equipment; it is not promised before review."], ["Is equipment included?", "Labour, patch leads, panels, connectors and modules are separated to avoid hidden costs."]],
  } : {
    problems: isEs ? ["No funciona la llamada, audio o vídeo", "El abrepuertas no responde", "El sistema antiguo necesita sustitución o ampliación"] : ["Call, audio or video is not working", "Door release does not respond", "An older system needs replacement or expansion"],
    uses: isEs ? ["Pisos y viviendas", "Puertas y portones", "Oficinas y negocios", "Comunidades, tras revisión del sistema"] : ["Apartments and homes", "Doors and gates", "Offices and businesses", "Residential buildings after system review"],
    process: isEs ? ["Identificamos placa, monitor y fuente", "Revisamos cableado y apertura", "Confirmamos compatibilidad o alternativa", "Instalamos, configuramos y probamos"] : ["Identify panel, monitor and power supply", "Review cabling and door release", "Confirm compatibility or an alternative", "Install, configure and test"],
    faq: isEs ? [["¿Se puede aprovechar el cableado?", "Depende de su estado y de la arquitectura del sistema nuevo; lo revisamos antes de proponer una sustitución."], ["¿Podéis integrar apertura de puerta?", "Sí, cuando cerradero, alimentación y control sean compatibles."], ["¿Trabajáis con Fermax y Tegui?", "Podemos instalar o revisar equipos compatibles de estas y otras marcas, sin afirmar partnership oficial."]] : [["Can existing cabling be reused?", "It depends on its condition and the new system architecture; we review it before recommending replacement."], ["Can you integrate door release?", "Yes, where the strike, power and control are compatible."], ["Do you work with Fermax and Tegui?", "We can install or review compatible equipment from these and other brands, without claiming official partnership."]],
  };
  const categoryPath = category === "fiber" ? "services/fiber" : "services/intercom";
  const jsonLd = [{ "@context": "https://schema.org", "@type": "Service", name: title, url: localizedUrl(locale, categoryPath), areaServed: { "@type": "City", name: "Valencia" }, provider: { "@id": "https://www.thevulgo.es/#localbusiness" } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: pillar.faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }];
  return <main className="bg-white text-neutral-950">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="bg-neutral-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-yellow-400/40 px-4 py-2 text-xs font-black uppercase tracking-[.15em] text-yellow-400"><Icon className="h-4 w-4" />THEVULGO SECURITY & NETWORKS</div><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-6xl">{category === "fiber" ? (isEs ? "Instalación y reparación de fibra óptica en Valencia" : "Fiber Optic Installation & Repair in Valencia") : (isEs ? "Videoporteros y sistemas de entrada en Valencia" : "Intercom & Door Entry Systems in Valencia")}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-neutral-300">{category === "fiber" ? (isEs ? "Fibra para backbone, racks, enlaces entre zonas, terminación, fusión y diagnóstico de averías." : "Fiber for backbones, racks, links between areas, termination, splicing and fault diagnosis.") : (isEs ? "Videoporteros IP o convencionales, entrada de puertas y portones, apertura e integración con control de acceso." : "IP and conventional intercoms, door and gate entry, release control and access-system integration.")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`${localizedPath(locale, "estimate")}?category=${category}`} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-yellow-400 px-6 py-4 font-black text-black">{isEs ? "Calcular presupuesto" : "Get project estimate"}<ArrowRight className="h-5 w-5" /></Link><a href={technicalWhatsAppHref(category, locale)} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl border border-neutral-600 px-6 py-4 font-black"><MessageCircle className="h-5 w-5 text-yellow-400" />WhatsApp</a></div></div><div className="rounded-3xl border border-neutral-700 bg-neutral-900 p-7"><p className="text-sm font-black text-yellow-400">{isEs ? "Instalación nueva y sistemas existentes" : "New installations and existing systems"}</p><div className="mt-5 space-y-4">{(category === "fiber" ? (isEs ? ["Monomodo y multimodo", "LC y SC", "Racks y patch panels", "SFP / SFP+", "Diagnóstico y reparación"] : ["Single-mode and multimode", "LC and SC", "Racks and patch panels", "SFP / SFP+", "Diagnosis and repair"]) : (isEs ? ["Audio y vídeo", "Monitor interior y app", "Portones y puertas", "Cerradero eléctrico", "Sistemas IP"] : ["Audio and video", "Indoor monitor and app", "Gates and doors", "Electric strike", "IP systems"])).map((text) => <div key={text} className="flex gap-3"><CheckCircle2 className="h-5 w-5 text-yellow-400" /><span>{text}</span></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.16em] text-yellow-600">{title}</p><h2 className="mt-2 text-3xl font-black">{isEs ? "Elige el servicio técnico" : "Choose the technical service"}</h2></div><Link href={localizedPath(locale, "services/security-networks")} className="font-bold underline decoration-yellow-400 underline-offset-4">{isEs ? "Ver toda la división técnica" : "View the full technical division"}</Link></div><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Link key={item.id} href={localizedPath(locale, technicalLeafPath(item))} className="group flex min-h-64 flex-col rounded-2xl border border-neutral-200 p-6 shadow-sm transition hover:-translate-y-1 hover:border-yellow-400 hover:shadow-xl"><Icon className="h-7 w-7 text-yellow-500" /><h3 className="mt-6 text-xl font-black">{item.h1[language]}</h3><p className="mt-3 flex-1 text-sm leading-6 text-neutral-600">{item.intro[language]}</p><span className="mt-5 inline-flex items-center gap-2 font-black">{isEs ? "Ver servicio" : "View service"}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section>
    <section className="border-y border-neutral-200 bg-neutral-50"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:px-8 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[.16em] text-yellow-600">{isEs ? "Problemas y aplicaciones" : "Problems and applications"}</p><h2 className="mt-3 text-3xl font-black">{isEs ? "Instalación nueva y mejora de sistemas existentes" : "New installation and existing-system upgrades"}</h2><div className="mt-7 grid gap-3">{pillar.problems.map((item) => <div key={item} className="rounded-2xl bg-white p-5 font-bold shadow-sm">{item}</div>)}</div></div><div className="rounded-3xl bg-neutral-950 p-7 text-white"><h2 className="text-2xl font-black">{isEs ? "Viviendas y negocios" : "Homes and businesses"}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{pillar.uses.map((item) => <div key={item} className="flex gap-2 text-sm text-neutral-200"><CheckCircle2 className="h-5 w-5 shrink-0 text-yellow-400" />{item}</div>)}</div><p className="mt-7 border-t border-neutral-700 pt-6 text-sm leading-6 text-neutral-400">{isEs ? "Equipos y materiales se confirman por separado después de revisar compatibilidad, cantidades y recorrido." : "Equipment and materials are confirmed separately after compatibility, quantities and route are reviewed."}</p></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-black uppercase tracking-[.16em] text-yellow-600">{isEs ? "Cómo trabajamos" : "How it works"}</p><h2 className="mt-3 text-3xl font-black">{isEs ? "Un alcance técnico comprensible" : "A clear technical scope"}</h2><div className="mt-7 space-y-3">{pillar.process.map((item, index) => <div key={item} className="flex gap-4 rounded-2xl border border-neutral-200 p-5"><span className="font-black text-yellow-600">{index + 1}</span><span className="font-bold">{item}</span></div>)}</div></div><div><h2 className="text-3xl font-black">FAQ</h2><div className="mt-7 space-y-3">{pillar.faq.map(([question, answer]) => <details key={question} className="rounded-2xl border border-neutral-200 p-5"><summary className="cursor-pointer font-black">{question}</summary><p className="mt-3 text-sm leading-6 text-neutral-600">{answer}</p></details>)}</div></div></div></section>
    <section className="bg-neutral-950 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-12 md:px-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-black">{isEs ? "¿No sabes qué solución necesitas?" : "Not sure which solution you need?"}</h2><p className="mt-2 text-neutral-300">{isEs ? "Una visita técnica permite revisar compatibilidad, recorrido y equipo existente." : "A technical visit can establish compatibility, route and existing equipment."}</p></div><Link href={`${localizedPath(locale, "estimate")}?category=${category}&service=${category}-diagnostic`} className="inline-flex min-h-14 items-center justify-center rounded-xl bg-yellow-400 px-6 py-4 font-black text-black">{isEs ? "Visita técnica · 49 €" : "Technical visit · €49"}</Link></div></section>
  </main>;
}
