import Link from "next/link";
import { ArrowRight, Cable, CheckCircle2, MessageCircle, Radio } from "lucide-react";
import { getTechnicalLeaves, TECHNICAL_CATEGORY_LABELS, technicalLeafPath, type TechnicalCategoryId } from "@/lib/securityNetworkCatalog";
import { localizedPath } from "@/lib/technicalRoutes";
import { technicalWhatsAppHref } from "@/lib/technicalWhatsApp";

export default function TechnicalCategoryHub({ category, locale }: { category: TechnicalCategoryId; locale: string }) {
  const language = locale === "es" ? "es" : "en";
  const isEs = language === "es";
  const items = getTechnicalLeaves(category);
  const Icon = category === "fiber" ? Cable : Radio;
  const title = TECHNICAL_CATEGORY_LABELS[category][language];
  return <main className="bg-white text-neutral-950">
    <section className="bg-neutral-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-yellow-400/40 px-4 py-2 text-xs font-black uppercase tracking-[.15em] text-yellow-400"><Icon className="h-4 w-4" />THEVULGO SECURITY & NETWORKS</div><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-6xl">{category === "fiber" ? (isEs ? "Instalación y reparación de fibra óptica en Valencia" : "Fiber Optic Installation & Repair in Valencia") : (isEs ? "Videoporteros y sistemas de entrada en Valencia" : "Intercom & Door Entry Systems in Valencia")}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-neutral-300">{category === "fiber" ? (isEs ? "Fibra para backbone, racks, enlaces entre zonas, terminación, fusión y diagnóstico de averías." : "Fiber for backbones, racks, links between areas, termination, splicing and fault diagnosis.") : (isEs ? "Videoporteros IP o convencionales, entrada de puertas y portones, apertura e integración con control de acceso." : "IP and conventional intercoms, door and gate entry, release control and access-system integration.")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`${localizedPath(locale, "estimate")}?category=${category}`} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-yellow-400 px-6 py-4 font-black text-black">{isEs ? "Calcular presupuesto" : "Get project estimate"}<ArrowRight className="h-5 w-5" /></Link><a href={technicalWhatsAppHref(category, locale)} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl border border-neutral-600 px-6 py-4 font-black"><MessageCircle className="h-5 w-5 text-yellow-400" />WhatsApp</a></div></div><div className="rounded-3xl border border-neutral-700 bg-neutral-900 p-7"><p className="text-sm font-black text-yellow-400">{isEs ? "Instalación nueva y sistemas existentes" : "New installations and existing systems"}</p><div className="mt-5 space-y-4">{(category === "fiber" ? (isEs ? ["Monomodo y multimodo", "LC y SC", "Racks y patch panels", "SFP / SFP+", "Diagnóstico y reparación"] : ["Single-mode and multimode", "LC and SC", "Racks and patch panels", "SFP / SFP+", "Diagnosis and repair"]) : (isEs ? ["Audio y vídeo", "Monitor interior y app", "Portones y puertas", "Cerradero eléctrico", "Sistemas IP"] : ["Audio and video", "Indoor monitor and app", "Gates and doors", "Electric strike", "IP systems"])).map((text) => <div key={text} className="flex gap-3"><CheckCircle2 className="h-5 w-5 text-yellow-400" /><span>{text}</span></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.16em] text-yellow-600">{title}</p><h2 className="mt-2 text-3xl font-black">{isEs ? "Elige el servicio técnico" : "Choose the technical service"}</h2></div><Link href={localizedPath(locale, "services/security-networks")} className="font-bold underline decoration-yellow-400 underline-offset-4">{isEs ? "Ver toda la división técnica" : "View the full technical division"}</Link></div><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Link key={item.id} href={localizedPath(locale, technicalLeafPath(item))} className="group flex min-h-64 flex-col rounded-2xl border border-neutral-200 p-6 shadow-sm transition hover:-translate-y-1 hover:border-yellow-400 hover:shadow-xl"><Icon className="h-7 w-7 text-yellow-500" /><h3 className="mt-6 text-xl font-black">{item.h1[language]}</h3><p className="mt-3 flex-1 text-sm leading-6 text-neutral-600">{item.intro[language]}</p><span className="mt-5 inline-flex items-center gap-2 font-black">{isEs ? "Ver servicio" : "View service"}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section>
    <section className="bg-neutral-950 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-12 md:px-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-black">{isEs ? "¿No sabes qué solución necesitas?" : "Not sure which solution you need?"}</h2><p className="mt-2 text-neutral-300">{isEs ? "Una visita técnica permite revisar compatibilidad, recorrido y equipo existente." : "A technical visit can establish compatibility, route and existing equipment."}</p></div><Link href={`${localizedPath(locale, "estimate")}?category=${category}&service=${category}-diagnostic`} className="inline-flex min-h-14 items-center justify-center rounded-xl bg-yellow-400 px-6 py-4 font-black text-black">{isEs ? "Visita técnica · 49 €" : "Technical visit · €49"}</Link></div></section>
  </main>;
}
