import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, CheckCircle2, Clock3, MapPin, MessageCircle, ShieldCheck, Sparkles, Wind, Wrench } from "lucide-react";
import { getCatalogServices } from "@/lib/serviceCatalog";
import { AC_SEO_PAGES } from "@/lib/acSeoPages";
import WhatsAppLink from "@/app/components/WhatsAppLink";

type Props = { params: Promise<{ locale: string }> };
const baseUrl = "https://www.thevulgo.es";

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const isEs = locale === "es";
  const title = isEs ? "Aire acondicionado en Valencia | Reparación, limpieza e instalación | THEVULGO" : "Air Conditioning in Valencia | Repair, Cleaning & Installation | THEVULGO";
  const description = isEs ? "Diagnóstico, reparación, limpieza, mantenimiento, recarga de gas e instalación de aire acondicionado en Valencia." : "Air conditioning diagnostics, repair, cleaning, maintenance, refrigerant recharge and installation in Valencia.";
  return { title, description, alternates: { canonical: `${baseUrl}/${locale}/services/aire-acondicionado`, languages: { es: `${baseUrl}/es/services/aire-acondicionado`, en: `${baseUrl}/en/services/aire-acondicionado` } }, openGraph: { title, description, url: `${baseUrl}/${locale}/services/aire-acondicionado`, siteName: "THEVULGO", type: "website" } };
}

export default async function AirConditioningPage({ params }: Props) {
  const { locale } = await params;
  const isEs = locale === "es";
  const estimateHref = `/${locale}/estimate?category=air-conditioning`;
  const services = getCatalogServices("Air Conditioning");
  const popular = ["ac-diagnostic", "ac-not-cooling", "ac-basic-cleaning", "ac-r32-recharge", "ac-split-install", "ac-emergency"].map((id) => services.find((service) => service.id === id)).filter((service): service is NonNullable<typeof service> => Boolean(service));
  const highlights = isEs ? ["Diagnóstico y reparación", "Limpieza y desinfección", "Gas refrigerante y fugas", "Instalación de split y multisplit"] : ["Diagnostics and repair", "Cleaning and disinfection", "Refrigerant and leaks", "Split and multi-split installation"];
  const steps = isEs ? [["Cuéntanos qué pasa", "Envía una breve descripción, fotos o el código de error."], ["Confirmamos la visita", "Revisamos tu zona y la disponibilidad."], ["Revisamos el equipo", "Diagnosticamos el problema y confirmamos el trabajo."], ["Trabajo y prueba final", "Dejamos el equipo funcionando y el espacio limpio."]] : [["Tell us what is happening", "Send a short description, photos or the error code."], ["We confirm the visit", "We review your area and availability."], ["We inspect the unit", "We diagnose the issue and confirm the work."], ["Work and final test", "We leave the unit working and the space clean."]];
  const price = (service: (typeof services)[number]) => isEs ? service.priceLabelEs?.replace(/^desde\s+/i, "") || `${service.price} €` : service.priceLabel?.replace(/^from\s+/i, "") || `€${service.price}`;
  const destinations = AC_SEO_PAGES.filter((page) => page.category !== "guide");
  const prices = isEs ? [["Diagnóstico de aire acondicionado", "49 €"], ["Aire acondicionado no enfría / no calienta", "79 €"], ["Limpieza básica de split", "79 €"], ["Limpieza profunda y desinfección", "109 €"], ["Recarga de gas R32", "129 €"], ["Instalación Split 1x1", "279 €"], ["Instalación Multi-Split 2x1", "449 €"], ["Instalación por conductos con preinstalación", "499 €"]] : [["Air conditioning diagnostic", "€49"], ["Not cooling / not heating", "€79"], ["Basic split AC cleaning", "€79"], ["Deep cleaning and disinfection", "€109"], ["R32 refrigerant recharge", "€129"], ["Split 1x1 installation", "€279"], ["Multi-split 2x1 installation", "€449"], ["Ducted installation with existing pre-installation", "€499"]];
  const whyChoose = isEs ? ["Diagnóstico claro antes de reparar", "Precio y alcance confirmados antes de empezar", "Limpieza del área al terminar", "Servicio para viviendas, pisos, Airbnb y negocios", "Atención rápida por WhatsApp", "Trabajo adaptado al tipo de equipo y acceso"] : ["Clear diagnostics before repair", "Price and scope confirmed before work starts", "Clean work area when finished", "Service for homes, apartments, Airbnb and businesses", "Fast WhatsApp communication", "Work adapted to the unit and site access"];
  const areas = ["Valencia", "Ruzafa", "Campanar", "Benimaclet", "Patraix", "El Carmen", "Mislata", "Burjassot", "Paterna", "Torrent", "Alboraya", "Manises"];
  const faqs = isEs ? [{ q: "¿El diagnóstico se descuenta de la reparación?", a: "Primero revisamos el equipo y confirmamos el alcance. La aplicación del diagnóstico a la reparación depende del trabajo confirmado; lo aclaramos antes de empezar." }, { q: "¿Podéis reparar un equipo que no enfría?", a: "Sí. Revisamos filtros, desagüe, ventilación, presión, posibles fugas y componentes accesibles para proponer el siguiente paso." }, { q: "¿Incluye la limpieza la unidad exterior?", a: "Hay servicios para unidad interior, limpieza completa de interior y exterior, y mantenimiento de sistemas por conductos. Elige la opción que encaje con tu equipo." }, { q: "¿Trabajáis con R32 y R410A?", a: "Podemos revisar la presión, localizar fugas y gestionar recargas según el refrigerante y el estado del equipo." }, { q: "¿Podéis instalar un aire acondicionado nuevo?", a: "Sí, trabajamos con split, multisplit, conductos, cassette y bomba de calor. Comparte fotos y detalles de la preinstalación para confirmar el alcance." }] : [{ q: "Is the diagnostic fee deducted from the repair?", a: "We inspect the unit first and confirm the scope. Whether the diagnostic is applied to the repair depends on the confirmed work; we clarify this before starting." }, { q: "Can you repair an AC unit that is not cooling?", a: "Yes. We check filters, drainage, airflow, pressure, possible leaks and accessible components to propose the next step." }, { q: "Does cleaning include the outdoor unit?", a: "We offer indoor-unit, full indoor-and-outdoor, and ducted-system maintenance options. Choose the service that fits your unit." }, { q: "Do you work with R32 and R410A?", a: "We can check pressure, locate leaks and handle recharge work according to the refrigerant and unit condition." }, { q: "Can you install a new AC unit?", a: "Yes. We work with split, multi-split, ducted, cassette and heat-pump systems. Send photos and pre-installation details to confirm the scope." }];
  const serviceJsonLd = { "@context": "https://schema.org", "@type": "Service", name: isEs ? "Aire acondicionado en Valencia" : "Air conditioning in Valencia", areaServed: "Valencia", provider: { "@type": "HomeAndConstructionBusiness", name: "THEVULGO", telephone: "+34610076942" } };

  return <main className="overflow-hidden bg-white text-black"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceJsonLd) }} />
    <section className="relative px-4 pb-16 pt-16 sm:pb-24 sm:pt-24"><div className="absolute inset-0 -z-10 bg-gradient-to-b from-yellow-50 via-white to-white" /><div className="absolute -right-24 top-12 -z-10 h-80 w-80 rounded-full bg-yellow-200/50 blur-3xl" />
      <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-yellow-400 bg-white px-4 py-2 text-sm font-bold shadow-sm"><Wind className="h-4 w-4" />{isEs ? "Climatización · Valencia" : "Air conditioning · Valencia"}</div><h1 className="mt-6 text-5xl font-black leading-[.96] tracking-tight sm:text-6xl">{isEs ? <>Aire acondicionado<br /><span className="text-yellow-500">sin sorpresas.</span></> : <>Air conditioning<br /><span className="text-yellow-500">with no surprises.</span></>}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-neutral-600">{isEs ? "Reparación, limpieza, recarga de gas e instalación. Confirmamos el alcance antes de empezar." : "Repair, cleaning, refrigerant recharge and installation. We confirm the scope before getting started."}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={estimateHref} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-yellow-400 px-7 py-4 font-black shadow-lg transition hover:scale-[1.02]">{isEs ? "Pedir presupuesto" : "Get an estimate"}<ArrowRight className="h-5 w-5" /></Link><WhatsAppLink source="ac-main-hero" service="air-conditioning" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-neutral-300 bg-white px-7 py-4 font-black"><MessageCircle className="h-5 w-5" />WhatsApp</WhatsAppLink></div><div className="mt-8 flex flex-wrap gap-3 text-sm font-semibold text-neutral-700"><span className="inline-flex items-center gap-1.5"><Clock3 className="h-4 w-4 text-yellow-500" />{isEs ? "Respuesta rápida" : "Fast reply"}</span><span className="inline-flex items-center gap-1.5"><MapPin className="h-4 w-4 text-yellow-500" />Valencia</span><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-yellow-500" />{isEs ? "Precio confirmado" : "Price confirmed"}</span></div></div>
      <div className="rounded-[2rem] border-2 border-yellow-400 bg-neutral-950 p-7 text-white shadow-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-yellow-400">THEVULGO</p><h2 className="mt-3 text-3xl font-black">{isEs ? "¿Qué necesitas?" : "What do you need?"}</h2><div className="mt-6 space-y-4">{highlights.map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-white/10 p-4"><CheckCircle2 className="h-5 w-5 shrink-0 text-yellow-400" /><span className="font-bold">{item}</span></div>)}</div><Link href={estimateHref} className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-yellow-400 px-5 py-4 font-black text-black">{isEs ? "Ver precios y servicios" : "View services and prices"}<ArrowRight className="h-5 w-5" /></Link></div></div>
    </section>
    <section className="bg-neutral-950 px-4 py-16 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-400">{isEs ? "Servicios principales" : "Popular services"}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{isEs ? "Elige el servicio que mejor describe tu caso" : "Choose the service that best describes your need"}</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{popular.map((service) => <Link key={service.id} href={estimateHref} className="rounded-2xl border border-white/15 bg-white/5 p-5 transition hover:border-yellow-400 hover:bg-white/10"><p className="font-extrabold">{isEs ? service.labelEs : service.label}</p><p className="mt-3 text-lg font-black text-yellow-400">{price(service)}</p></Link>)}</div></div></section>
    <section className="px-4 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-600">{isEs ? "Precios claros" : "Clear pricing"}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{isEs ? "Servicios de aire acondicionado y precios orientativos" : "Air conditioning services and guide prices"}</h2><p className="mt-5 leading-8 text-neutral-600">{isEs ? "Cada equipo y cada instalación tienen condiciones distintas. Los precios muestran el punto de partida; confirmamos el trabajo, materiales y acceso antes de realizarlo." : "Each unit and installation has different conditions. Prices show the starting point; we confirm work, materials and access before we carry it out."}</p><Link href={estimateHref} className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-yellow-400 px-6 py-4 font-black">{isEs ? "Ver todos los servicios" : "View all services"}<ArrowRight className="h-5 w-5" /></Link></div><div className="overflow-hidden rounded-3xl border border-neutral-200 bg-white shadow-lg">{prices.map(([name, amount]) => <div key={name} className="flex items-center justify-between gap-4 border-b border-neutral-100 px-5 py-4 last:border-0"><span className="font-semibold">{name}</span><strong className="shrink-0 text-yellow-600">{amount}</strong></div>)}</div></div></section>
    <section className="bg-yellow-50 px-4 py-16 sm:py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-600">{isEs ? "Por qué THEVULGO" : "Why THEVULGO"}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{isEs ? "Una visita organizada de principio a fin" : "An organised visit from start to finish"}</h2></div><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{whyChoose.map((item) => <div key={item} className="flex gap-3 rounded-2xl border border-yellow-200 bg-white p-5 shadow-sm"><CheckCircle2 className="h-5 w-5 shrink-0 text-yellow-500" /><span className="font-bold">{item}</span></div>)}</div></div></section>
    <section className="px-4 py-16 sm:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-600">{isEs ? "Proceso claro" : "Clear process"}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{isEs ? "Así organizamos tu visita" : "How we arrange your visit"}</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map(([title, text], index) => <article key={title} className="rounded-3xl border border-neutral-200 p-6 shadow-sm"><BadgeCheck className="h-7 w-7 text-yellow-500" /><p className="mt-5 text-xs font-black text-yellow-600">0{index + 1}</p><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-neutral-600">{text}</p></article>)}</div></div></section>
    <section className="px-4 py-16"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-600">{isEs ? "Guía de servicios" : "Service guide"}</p><h2 className="mt-3 text-3xl font-black">{isEs ? "Encuentra tu caso" : "Find your case"}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{destinations.map((destination) => <Link key={destination.path} href={`/${locale}/${destination.path}`} className="rounded-xl border border-neutral-200 p-4 text-sm font-bold transition hover:border-yellow-400 hover:bg-yellow-50">{isEs ? destination.titleEs : destination.titleEn}</Link>)}</div></div></section>
    <section className="bg-neutral-950 px-4 py-16 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-400">{isEs ? "Zona de servicio" : "Service area"}</p><h2 className="mt-3 text-3xl font-black">{isEs ? "Aire acondicionado en Valencia y alrededores" : "Air conditioning in Valencia and nearby areas"}</h2><p className="mt-5 max-w-2xl leading-8 text-neutral-300">{isEs ? "Trabajamos en Valencia y municipios cercanos. Si tu zona no aparece, envíanos la ubicación por WhatsApp y confirmamos disponibilidad antes de reservar." : "We work in Valencia and nearby municipalities. If your area is not listed, send us your location on WhatsApp and we will confirm availability before booking."}</p></div><div className="flex flex-wrap content-start gap-2">{areas.map((area) => <span key={area} className="rounded-full border border-white/20 bg-white/5 px-4 py-2 text-sm font-bold">{area}</span>)}</div></div></div></section>
    <section className="px-4 py-16 sm:py-24"><div className="mx-auto max-w-5xl"><p className="text-center text-sm font-black uppercase tracking-[.18em] text-yellow-600">FAQ</p><h2 className="mt-3 text-center text-3xl font-black sm:text-4xl">{isEs ? "Preguntas frecuentes sobre aire acondicionado" : "Frequently asked air conditioning questions"}</h2><div className="mt-10 space-y-4">{faqs.map((faq) => <article key={faq.q} className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm"><h3 className="text-lg font-black">{faq.q}</h3><p className="mt-3 leading-7 text-neutral-600">{faq.a}</p></article>)}</div></div></section>
    <section className="bg-yellow-50 px-4 py-16"><div className="mx-auto max-w-5xl rounded-[2rem] border border-yellow-400 bg-white p-8 text-center shadow-xl sm:p-12"><Sparkles className="mx-auto h-8 w-8 text-yellow-500" /><h2 className="mt-4 text-3xl font-black">{isEs ? "¿No encuentras tu caso?" : "Can't find your case?"}</h2><p className="mx-auto mt-4 max-w-2xl text-neutral-600">{isEs ? "Envíanos fotos, marca y modelo del equipo. Te orientamos antes de reservar." : "Send us photos, the make and model of your unit. We will guide you before you book."}</p><Link href={estimateHref} className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-yellow-400 px-7 py-4 font-black"><Wrench className="h-5 w-5" />{isEs ? "Solicitar presupuesto" : "Request an estimate"}</Link></div></section>
  </main>;
}
