import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, CheckCircle2, Clock3, MapPin, MessageCircle, ShieldCheck, Sparkles, Wind, Wrench } from "lucide-react";
import { getCatalogServices } from "@/lib/serviceCatalog";

type Props = { params: Promise<{ locale: string }> };
const baseUrl = "https://www.thevulgo.es";
const phone = "34610076942";

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const isEs = locale === "es";
  const title = isEs ? "Aire acondicionado en Valencia | Reparación, limpieza e instalación | THEVULGO" : "Air Conditioning in Valencia | Repair, Cleaning & Installation | THEVULGO";
  const description = isEs ? "Diagnóstico, reparación, limpieza, mantenimiento, recarga de gas e instalación de aire acondicionado en Valencia." : "Air conditioning diagnostics, repair, cleaning, maintenance, refrigerant recharge and installation in Valencia.";
  return { title, description, alternates: { canonical: `${baseUrl}/${locale}/services/aire-acondicionado`, languages: { es: `${baseUrl}/es/services/aire-acondicionado`, en: `${baseUrl}/en/services/aire-acondicionado` } }, openGraph: { title, description, url: `${baseUrl}/${locale}/services/aire-acondicionado`, siteName: "THEVULGO", type: "website" } };
}

export default async function AirConditioningPage({ params }: Props) {
  const { locale } = await params;
  const isEs = locale === "es";
  const estimateHref = `/${locale}/estimate?category=air-conditioning`;
  const whatsapp = `https://wa.me/${phone}?text=${encodeURIComponent(isEs ? "Hola, necesito ayuda con el aire acondicionado en Valencia. Quiero pedir presupuesto." : "Hi, I need help with air conditioning in Valencia. I'd like an estimate.")}`;
  const services = getCatalogServices("Air Conditioning");
  const popular = ["ac-diagnostic", "ac-not-cooling", "ac-basic-cleaning", "ac-r32-recharge", "ac-split-install", "ac-emergency"].map((id) => services.find((service) => service.id === id)).filter((service): service is NonNullable<typeof service> => Boolean(service));
  const highlights = isEs ? ["Diagnóstico y reparación", "Limpieza y desinfección", "Gas refrigerante y fugas", "Instalación de split y multisplit"] : ["Diagnostics and repair", "Cleaning and disinfection", "Refrigerant and leaks", "Split and multi-split installation"];
  const steps = isEs ? [["Cuéntanos qué pasa", "Envía una breve descripción, fotos o el código de error."], ["Confirmamos la visita", "Revisamos tu zona y la disponibilidad."], ["Revisamos el equipo", "Diagnosticamos el problema y confirmamos el trabajo."], ["Trabajo y prueba final", "Dejamos el equipo funcionando y el espacio limpio."]] : [["Tell us what is happening", "Send a short description, photos or the error code."], ["We confirm the visit", "We review your area and availability."], ["We inspect the unit", "We diagnose the issue and confirm the work."], ["Work and final test", "We leave the unit working and the space clean."]];
  const price = (service: (typeof services)[number]) => isEs ? service.priceLabelEs?.replace(/^desde\s+/i, "") || `${service.price} €` : service.priceLabel?.replace(/^from\s+/i, "") || `€${service.price}`;
  const serviceJsonLd = { "@context": "https://schema.org", "@type": "Service", name: isEs ? "Aire acondicionado en Valencia" : "Air conditioning in Valencia", areaServed: "Valencia", provider: { "@type": "HomeAndConstructionBusiness", name: "THEVULGO", telephone: `+${phone}` } };

  return <main className="overflow-hidden bg-white text-black"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceJsonLd) }} />
    <section className="relative px-4 pb-16 pt-16 sm:pb-24 sm:pt-24"><div className="absolute inset-0 -z-10 bg-gradient-to-b from-yellow-50 via-white to-white" /><div className="absolute -right-24 top-12 -z-10 h-80 w-80 rounded-full bg-yellow-200/50 blur-3xl" />
      <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-yellow-400 bg-white px-4 py-2 text-sm font-bold shadow-sm"><Wind className="h-4 w-4" />{isEs ? "Climatización · Valencia" : "Air conditioning · Valencia"}</div><h1 className="mt-6 text-5xl font-black leading-[.96] tracking-tight sm:text-6xl">{isEs ? <>Aire acondicionado<br /><span className="text-yellow-500">sin sorpresas.</span></> : <>Air conditioning<br /><span className="text-yellow-500">with no surprises.</span></>}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-neutral-600">{isEs ? "Reparación, limpieza, recarga de gas e instalación. Confirmamos el alcance antes de empezar." : "Repair, cleaning, refrigerant recharge and installation. We confirm the scope before getting started."}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={estimateHref} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-yellow-400 px-7 py-4 font-black shadow-lg transition hover:scale-[1.02]">{isEs ? "Pedir presupuesto" : "Get an estimate"}<ArrowRight className="h-5 w-5" /></Link><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-neutral-300 bg-white px-7 py-4 font-black"><MessageCircle className="h-5 w-5" />WhatsApp</a></div><div className="mt-8 flex flex-wrap gap-3 text-sm font-semibold text-neutral-700"><span className="inline-flex items-center gap-1.5"><Clock3 className="h-4 w-4 text-yellow-500" />{isEs ? "Respuesta rápida" : "Fast reply"}</span><span className="inline-flex items-center gap-1.5"><MapPin className="h-4 w-4 text-yellow-500" />Valencia</span><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-4 w-4 text-yellow-500" />{isEs ? "Precio confirmado" : "Price confirmed"}</span></div></div>
      <div className="rounded-[2rem] border-2 border-yellow-400 bg-neutral-950 p-7 text-white shadow-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-yellow-400">THEVULGO</p><h2 className="mt-3 text-3xl font-black">{isEs ? "¿Qué necesitas?" : "What do you need?"}</h2><div className="mt-6 space-y-4">{highlights.map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-white/10 p-4"><CheckCircle2 className="h-5 w-5 shrink-0 text-yellow-400" /><span className="font-bold">{item}</span></div>)}</div><Link href={estimateHref} className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-yellow-400 px-5 py-4 font-black text-black">{isEs ? "Ver precios y servicios" : "View services and prices"}<ArrowRight className="h-5 w-5" /></Link></div></div>
    </section>
    <section className="bg-neutral-950 px-4 py-16 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-400">{isEs ? "Servicios principales" : "Popular services"}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{isEs ? "Elige el servicio que mejor describe tu caso" : "Choose the service that best describes your need"}</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{popular.map((service) => <Link key={service.id} href={estimateHref} className="rounded-2xl border border-white/15 bg-white/5 p-5 transition hover:border-yellow-400 hover:bg-white/10"><p className="font-extrabold">{isEs ? service.labelEs : service.label}</p><p className="mt-3 text-lg font-black text-yellow-400">{price(service)}</p></Link>)}</div></div></section>
    <section className="px-4 py-16 sm:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-yellow-600">{isEs ? "Proceso claro" : "Clear process"}</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">{isEs ? "Así organizamos tu visita" : "How we arrange your visit"}</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map(([title, text], index) => <article key={title} className="rounded-3xl border border-neutral-200 p-6 shadow-sm"><BadgeCheck className="h-7 w-7 text-yellow-500" /><p className="mt-5 text-xs font-black text-yellow-600">0{index + 1}</p><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-neutral-600">{text}</p></article>)}</div></div></section>
    <section className="bg-yellow-50 px-4 py-16"><div className="mx-auto max-w-5xl rounded-[2rem] border border-yellow-400 bg-white p-8 text-center shadow-xl sm:p-12"><Sparkles className="mx-auto h-8 w-8 text-yellow-500" /><h2 className="mt-4 text-3xl font-black">{isEs ? "¿No encuentras tu caso?" : "Can't find your case?"}</h2><p className="mx-auto mt-4 max-w-2xl text-neutral-600">{isEs ? "Envíanos fotos, marca y modelo del equipo. Te orientamos antes de reservar." : "Send us photos, the make and model of your unit. We will guide you before you book."}</p><Link href={estimateHref} className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-yellow-400 px-7 py-4 font-black"><Wrench className="h-5 w-5" />{isEs ? "Solicitar presupuesto" : "Request an estimate"}</Link></div></section>
  </main>;
}
