import type { AcSeoPage } from "./acSeoPages";

type Locale = "es" | "en";

function text<T>(es: T, en: T, locale: Locale): T { return locale === "es" ? es : en; }

export function getAcSeoContent(page: AcSeoPage, locale: Locale) {
  const title = locale === "es" ? page.titleEs : page.titleEn;
  const isGuide = page.category === "guide";
  const kind = page.category;
  const intro = isGuide
    ? text(`Esta guía sobre ${title.toLowerCase()} explica los puntos que conviene revisar antes de tomar una decisión. Está pensada para viviendas y negocios de Valencia, con criterios prácticos para entender el equipo, comparar opciones y preparar una visita técnica.`, `This guide to ${title.toLowerCase()} explains the points worth checking before making a decision. It is designed for homes and businesses in Valencia, with practical criteria to understand the unit, compare options and prepare a technical visit.`, locale)
    : text(`${title} requiere revisar el equipo, el acceso y el alcance real del trabajo. En THEVULGO empezamos por entender el síntoma o la instalación, explicamos qué comprobamos y confirmamos el presupuesto antes de realizar cualquier intervención.`, `${title} requires checking the unit, access and the real scope of work. At THEVULGO we start by understanding the symptom or installation, explain what we check and confirm the estimate before carrying out any work.`, locale);
  const work = kind === "installation"
    ? text(["Revisión del lugar de montaje, distancia y accesos", "Comprobación de preinstalación, desagüe y alimentación disponible", "Instalación y puesta en marcha según el equipo y el alcance confirmado"], ["Review of the installation location, distance and access", "Check of pre-installation, drainage and available power", "Installation and commissioning according to the unit and confirmed scope"], locale)
    : kind === "ducted"
      ? text(["Revisión de retorno, rejillas, accesos y comportamiento del sistema", "Diagnóstico de mantenimiento, limpieza, fuga o avería según el caso", "Explicación de las opciones de trabajo antes de intervenir"], ["Review of returns, grilles, access and system behaviour", "Diagnosis of maintenance, cleaning, leak or fault according to the case", "Explanation of work options before intervention"], locale)
      : kind === "commercial"
        ? text(["Planificación según horarios, clientes, acceso y continuidad del negocio", "Revisión del equipo y de las prioridades operativas", "Propuesta clara para mantenimiento, reparación o mejora"], ["Planning around opening hours, customers, access and business continuity", "Review of the equipment and operational priorities", "Clear proposal for maintenance, repair or improvement"], locale)
        : text(["Revisión del síntoma, uso reciente y comportamiento del equipo", "Comprobación de los elementos que puedan afectar al funcionamiento", "Explicación del diagnóstico y confirmación del siguiente paso"], ["Review of the symptom, recent use and unit behaviour", "Check of the elements that can affect performance", "Explanation of the diagnosis and confirmation of the next step"], locale);
  const prep = text(["Comparte fotos de la unidad interior y exterior si puedes.", "Indica marca, modelo, código de error y desde cuándo ocurre el problema.", "Deja libre el acceso al equipo y avisa de normas del edificio, parking o escalera."], ["Share photos of the indoor and outdoor units if possible.", "Tell us the make, model, error code and when the issue started.", "Keep access to the unit clear and mention building rules, parking or stair access."], locale);
  const factors = text(["Tipo, antigüedad y estado del equipo", "Acceso a unidad interior, exterior o conductos", "Necesidad de piezas, materiales, metros adicionales o trabajos complementarios"], ["Type, age and condition of the unit", "Access to indoor, outdoor or ducted equipment", "Need for parts, materials, extra metres or complementary work"], locale);
  const faqs = isGuide
    ? [{ q: text(`¿Para quién sirve esta guía sobre ${title}?`, `Who is this guide to ${title} for?`, locale), a: text("Para personas que quieren entender las opciones antes de pedir presupuesto, comparar equipos o preparar información útil para una visita.", "For people who want to understand the options before requesting an estimate, comparing equipment or preparing useful information for a visit.", locale) }, { q: text("¿Una guía sustituye una revisión técnica?", "Does a guide replace a technical inspection?", locale), a: text("No. Las condiciones del equipo, la instalación y el acceso deben confirmarse en cada caso.", "No. The condition of the equipment, installation and access must be confirmed in each case.", locale) }]
    : [{ q: text(`¿Qué información ayuda para ${title.toLowerCase()}?`, `What information helps with ${title.toLowerCase()}?`, locale), a: text("Fotos, marca, modelo, síntomas, código de error y una breve descripción ayudan a orientar la visita y el alcance.", "Photos, make, model, symptoms, error code and a short description help guide the visit and scope.", locale) }, { q: text("¿El precio final se confirma antes?", "Is the final price confirmed beforehand?", locale), a: text("Sí. Revisamos el caso y explicamos el alcance, los materiales o factores que pueden cambiar el trabajo antes de continuar.", "Yes. We review the case and explain the scope, materials or factors that can change the work before continuing.", locale) }, { q: text("¿Trabajáis en Valencia y alrededores?", "Do you work in Valencia and nearby areas?", locale), a: text("Sí. Indica tu zona al solicitar presupuesto y confirmamos disponibilidad.", "Yes. Include your area when requesting an estimate and we will confirm availability.", locale) }];
  return { title, intro, work, prep, factors, faqs, isGuide };
}
