export type ServiceLabel = { es: string; en: string };

// Display labels are keyed by the final, stable URL segment. URLs remain unchanged.
export const SERVICE_LABELS: Readonly<Record<string, ServiceLabel>> = {
  "cambio-enchufe": { es: "Cambio de enchufe", en: "Socket replacement" },
  "cambio-interruptor": { es: "Cambio de interruptor", en: "Light switch replacement" },
  "cambio-lampara-techo": { es: "Cambio de lámpara de techo", en: "Ceiling light replacement" },
  "colgar-cuadros": { es: "Colocación de cuadros", en: "Picture hanging" },
  "colgar-espejos": { es: "Colocación de espejos", en: "Mirror hanging" },
  "colgar-tv": { es: "Instalación de TV en pared", en: "TV wall mounting" },
  "contratista-pladur": { es: "Contratista de pladur", en: "Drywall contractor" },
  electricista: { es: "Servicio de electricista", en: "Electrician service" },
  "empresa-pladur": { es: "Empresa de pladur", en: "Drywall company" },
  "falso-techo-pladur": { es: "Falso techo de pladur", en: "Drywall suspended ceiling" },
  "falsos-techos": { es: "Falsos techos", en: "Suspended ceilings" },
  handyman: { es: "Servicio de manitas", en: "Handyman service" },
  "home-cinema": { es: "Instalación de home cinema", en: "Home cinema installation" },
  "instalacion-armarios": { es: "Instalación de armarios", en: "Wardrobe installation" },
  "instalacion-barras-cortina": { es: "Instalación de barras de cortina", en: "Curtain rod installation" },
  "instalacion-lampara": { es: "Instalación de lámpara", en: "Light fitting installation" },
  "instalacion-lamparas-colgantes": { es: "Instalación de lámparas colgantes", en: "Pendant light installation" },
  "instalacion-pladur": { es: "Instalación de pladur", en: "Drywall installation" },
  "instalacion-proyectores": { es: "Instalación de proyectores", en: "Projector installation" },
  "instalacion-soporte-tv": { es: "Instalación de soporte de TV", en: "TV bracket installation" },
  "instalador-pladur": { es: "Instalador de pladur", en: "Drywall installer" },
  "instalador-tv": { es: "Instalador de TV", en: "TV installer" },
  "instalar-lampara": { es: "Instalación de lámpara", en: "Light installation" },
  "instalar-proyector-techo": { es: "Instalación de proyector en techo", en: "Ceiling projector installation" },
  "instalar-samsung-frame": { es: "Instalación de Samsung The Frame", en: "Samsung The Frame installation" },
  "instalar-tv-pared": { es: "Instalación de TV en pared", en: "TV wall installation" },
  "montaje-armario": { es: "Montaje de armario", en: "Wardrobe assembly" },
  "montaje-muebles": { es: "Montaje de muebles", en: "Furniture assembly" },
  "montaje-muebles-ikea": { es: "Montaje de muebles IKEA", en: "IKEA furniture assembly" },
  "montaje-proyector": { es: "Montaje de proyector", en: "Projector mounting" },
  "montaje-tv": { es: "Montaje de TV", en: "TV mounting" },
  "montaje-tv-65-pulgadas": { es: "Montaje de TV de 65 pulgadas", en: "65-inch TV mounting" },
  "montaje-tv-75-pulgadas": { es: "Montaje de TV de 75 pulgadas", en: "75-inch TV mounting" },
  "montaje-tv-85-pulgadas": { es: "Montaje de TV de 85 pulgadas", en: "85-inch TV mounting" },
  "montaje-tv-98-pulgadas": { es: "Montaje de TV de 98 pulgadas", en: "98-inch TV mounting" },
  "montaje-tv-grande": { es: "Montaje de TV grande", en: "Large TV mounting" },
  "montaje-tv-samsung-frame": { es: "Montaje de Samsung The Frame", en: "Samsung The Frame mounting" },
  "ocultar-cables": { es: "Ocultación de cables", en: "Cable concealment" },
  "pintar-pladur": { es: "Pintura de pladur", en: "Drywall painting" },
  pladur: { es: "Trabajos de pladur", en: "Drywall services" },
  "presupuesto-pladur": { es: "Presupuesto de pladur", en: "Drywall quote" },
  "reformas-pladur": { es: "Reformas con pladur", en: "Drywall renovation" },
  "reparacion-pladur": { es: "Reparación de pladur", en: "Drywall repair" },
  services: { es: "Todos los servicios", en: "All services" },
  alarmas: { es: "Instalación de alarmas", en: "Alarm installation" },
  bathroom: { es: "Trabajos de baño", en: "Bathroom jobs" },
  "accessory-installation": { es: "Instalación de accesorios de baño", en: "Bathroom accessory installation" },
  "cabinet-door-alignment": { es: "Ajuste de puertas de armario", en: "Cabinet door alignment" },
  "cabinet-installation": { es: "Instalación de mueble de baño", en: "Bathroom cabinet installation" },
  "glass-shelf-installation": { es: "Instalación de estante de cristal", en: "Glass shelf installation" },
  "mirror-cabinet-fitting": { es: "Instalación de armario con espejo", en: "Mirror cabinet fitting" },
  "mirror-installation": { es: "Instalación de espejo", en: "Mirror installation" },
  "multiple-installation-tasks": { es: "Varios trabajos de instalación", en: "Multiple installation tasks" },
  "seal-gap-fixing": { es: "Sellado de juntas", en: "Gap sealing" },
  "shelf-installation": { es: "Instalación de estante", en: "Shelf installation" },
  "shower-head-replacement": { es: "Cambio de alcachofa de ducha", en: "Shower head replacement" },
  "shower-hose-replacement": { es: "Cambio de flexo de ducha", en: "Shower hose replacement" },
  "silicone-renewal": { es: "Renovación de silicona", en: "Silicone renewal" },
  "toilet-paper-holder-installation": { es: "Instalación de portarrollos", en: "Toilet roll holder installation" },
  "towel-holder-installation": { es: "Instalación de toallero", en: "Towel rail installation" },
  "vanity-light-installation": { es: "Instalación de luz de espejo", en: "Vanity light installation" },
  "vanity-unit-installation": { es: "Instalación de mueble de lavabo", en: "Vanity unit installation" },
  "wall-mounting": { es: "Fijación en pared", en: "Wall mounting" },
  "cambio-lampara-por-ventilador": { es: "Cambio de lámpara por ventilador", en: "Light-to-ceiling-fan replacement" },
  cctv: { es: "Instalación de CCTV", en: "CCTV installation" },
  "control-de-acceso": { es: "Control de acceso", en: "Access control" },
  "devolver-piso-propietario": { es: "Preparación del piso para el propietario", en: "Rental handback preparation" },
  doors: { es: "Puertas y herrajes", en: "Doors and hardware" },
  "ajuste-cierrapuertas": { es: "Ajuste de cierrapuertas", en: "Door closer adjustment" },
  "cambio-bisagras-puerta": { es: "Cambio de bisagras de puerta", en: "Door hinge replacement" },
  "cambio-bombin-cerradura": { es: "Cambio de bombín de cerradura", en: "Lock cylinder replacement" },
  "door-alignment-adjustment": { es: "Ajuste de alineación de puerta", en: "Door alignment adjustment" },
  "door-seal-replacement": { es: "Cambio de burlete de puerta", en: "Door seal replacement" },
  "handle-replacement": { es: "Cambio de manilla", en: "Door handle replacement" },
  "herrajes-puertas-interiores": { es: "Herrajes para puertas interiores", en: "Interior door hardware" },
  "hinge-tightening": { es: "Ajuste de bisagras", en: "Hinge tightening" },
  "instalacion-tope-puerta": { es: "Instalación de tope de puerta", en: "Door stop installation" },
  "latch-adjustment": { es: "Ajuste de pestillo", en: "Latch adjustment" },
  "loose-handle-fixing": { es: "Ajuste de manilla suelta", en: "Loose handle repair" },
  "reparacion-puertas-varios": { es: "Reparaciones varias de puertas", en: "General door repairs" },
  drywall: { es: "Pladur y reparación de paredes", en: "Drywall and wall repair" },
  "anchor-hole-repair": { es: "Reparación de agujeros de tacos", en: "Wall anchor hole repair" },
  "cable-hole-closing": { es: "Cierre de agujeros para cables", en: "Cable hole repair" },
  "ceiling-spot-patching": { es: "Reparación puntual de techo", en: "Ceiling spot repair" },
  "concrete-wall-drilling": { es: "Perforación de pared de hormigón", en: "Concrete wall drilling" },
  "corner-repair": { es: "Reparación de esquinas", en: "Wall corner repair" },
  "crack-filling": { es: "Relleno de grietas", en: "Crack filling" },
  "door-handle-wall-damage-repair": { es: "Reparación de pared dañada por manilla", en: "Door-handle wall damage repair" },
  "drywall-cutout-repair": { es: "Reparación de recorte en pladur", en: "Drywall cutout repair" },
  "drywall-mounting-prep": { es: "Preparación de pladur para montaje", en: "Drywall mounting preparation" },
  "large-drywall-patch": { es: "Reparación grande de pladur", en: "Large drywall patch" },
  "medium-wall-patching": { es: "Reparación mediana de pared", en: "Medium wall patch" },
  "multiple-wall-repairs": { es: "Varias reparaciones de pared", en: "Multiple wall repairs" },
  "patch-and-sand-finish": { es: "Parcheado y lijado de pared", en: "Wall patching and sanding" },
  "shelf-removal-wall-repair": { es: "Reparación de pared tras retirar estante", en: "Wall repair after shelf removal" },
  "skim-coat-area-repair": { es: "Reparación con capa fina de masilla", en: "Skim-coat area repair" },
  "small-hole-repair": { es: "Reparación de agujeros en pared", en: "Small hole repair" },
  "tv-bracket-wall-repair": { es: "Reparación de pared tras retirar soporte de TV", en: "Wall repair after TV bracket removal" },
  "wall-drilling-service": { es: "Perforación de pared", en: "Wall drilling service" },
  "wall-levelling-prep": { es: "Preparación para nivelar paredes", en: "Wall levelling preparation" },
  "wall-touch-up-prep": { es: "Preparación de retoques de pared", en: "Wall touch-up preparation" },
  electrical: { es: "Electricidad básica", en: "Basic electrical work" },
  "cambio-extractor": { es: "Cambio de extractor", en: "Extractor fan replacement" },
  "cambio-luz-bano": { es: "Cambio de luz de baño", en: "Bathroom light replacement" },
  "instalacion-apliques-pared": { es: "Instalación de apliques de pared", en: "Wall light installation" },
  "instalacion-tira-led": { es: "Instalación de tira LED", en: "LED strip installation" },
  "montaje-electrico-basico": { es: "Montaje eléctrico básico", en: "Basic electrical installation" },
  exterior: { es: "Trabajos exteriores", en: "Exterior jobs" },
  "ajuste-accesorios-pergola-sombra": { es: "Ajuste de accesorios de pérgola", en: "Pergola accessory adjustment" },
  "ajuste-porton-exterio": { es: "Ajuste de portón exterior", en: "Exterior gate adjustment" },
  "instalacion-soportes-exteriores": { es: "Instalación de soportes exteriores", en: "Outdoor bracket installation" },
  "montaje-pared-exterior": { es: "Montaje en pared exterior", en: "Exterior wall mounting" },
  "reparacion-ajuste-vallas": { es: "Reparación y ajuste de vallas", en: "Fence repair and adjustment" },
  "reparacion-herrajes-exterior": { es: "Reparación de herrajes exteriores", en: "Outdoor hardware repair" },
  "retoques-fachada": { es: "Retoques de fachada", en: "Façade touch-ups" },
  "sellado-impermeable-exterior": { es: "Sellado impermeable exterior", en: "Exterior waterproof sealing" },
  "fin-contrato-alquiler": { es: "Puesta a punto al finalizar el alquiler", en: "End-of-tenancy repairs" },
  furniture: { es: "Montaje de muebles", en: "Furniture assembly" },
  "fijacion-muebles-pared": { es: "Fijación de muebles a pared", en: "Furniture wall anchoring" },
  "instalacion-estanterias": { es: "Instalación de estanterías", en: "Shelving installation" },
  "montaje-aparadores-muebles-auxiliares": { es: "Montaje de aparadores y muebles auxiliares", en: "Sideboard and occasional furniture assembly" },
  "montaje-cama": { es: "Montaje de cama", en: "Bed assembly" },
  "montaje-comodas-cajoneras": { es: "Montaje de cómodas y cajoneras", en: "Chest of drawers assembly" },
  "montaje-escritorios": { es: "Montaje de escritorios", en: "Desk assembly" },
  "montaje-estanterias": { es: "Montaje de estanterías", en: "Shelving assembly" },
  "montaje-mesas-comedor": { es: "Montaje de mesas de comedor", en: "Dining table assembly" },
  "montaje-muebles-tv-multimedia": { es: "Montaje de muebles de TV y multimedia", en: "TV and media unit assembly" },
  "montaje-sofas-modulares": { es: "Montaje de sofás modulares", en: "Modular sofa assembly" },
  "preparacion-muebles-mudanza": { es: "Preparación de muebles para mudanza", en: "Furniture preparation for moving" },
  "handyman-airbnb": { es: "Servicio de manitas para Airbnb", en: "Airbnb handyman service" },
  "instalacion-toldo-balcon": { es: "Instalación de toldo en balcón", en: "Balcony awning installation" },
  "instalacion-toldo-electrico": { es: "Instalación de toldo eléctrico", en: "Electric awning installation" },
  "instalacion-toldo-leroy-merlin": { es: "Instalación de toldo Leroy Merlin", en: "Leroy Merlin awning installation" },
  "instalacion-toldo-manual": { es: "Instalación de toldo manual", en: "Manual awning installation" },
  "instalacion-toldo-patio": { es: "Instalación de toldo en patio", en: "Patio awning installation" },
  "instalacion-toldo-terraza": { es: "Instalación de toldo en terraza", en: "Terrace awning installation" },
  "instalacion-toldos": { es: "Instalación de toldos", en: "Awning installation" },
  "instalacion-ventilador-control-remoto": { es: "Instalación de ventilador con mando", en: "Remote-control ceiling fan installation" },
  "instalacion-ventilador-smart": { es: "Instalación de ventilador inteligente", en: "Smart ceiling fan installation" },
  "instalacion-ventilador-techo": { es: "Instalación de ventilador de techo", en: "Ceiling fan installation" },
  "instalador-toldos": { es: "Instalador de toldos", en: "Awning installer" },
  "instalar-toldo": { es: "Instalación de toldo", en: "Awning installation" },
  "instalar-ventilador-techo": { es: "Instalación de ventilador de techo", en: "Ceiling fan installation" },
  kitchen: { es: "Trabajos de cocina", en: "Kitchen jobs" },
  "manitas-instalacion-toldos": { es: "Manitas para instalación de toldos", en: "Handyman awning installation" },
  "mantenimiento-airbnb": { es: "Mantenimiento para Airbnb", en: "Airbnb maintenance" },
  "montaje-toldo-leroy-merlin": { es: "Montaje de toldo Leroy Merlin", en: "Leroy Merlin awning assembly" },
  "montaje-toldos": { es: "Montaje de toldos", en: "Awning assembly" },
  "montaje-ventilador-techo": { es: "Montaje de ventilador de techo", en: "Ceiling fan assembly" },
  "move-in": { es: "Preparación de vivienda", en: "Move-in setup" },
  "pequenas-reparaciones": { es: "Pequeñas reparaciones", en: "Small repairs" },
  plumbing: { es: "Fontanería básica", en: "Basic plumbing" },
  "puesta-a-punto-piso": { es: "Puesta a punto de piso", en: "Flat preparation" },
  "puesta-a-punto-vivienda": { es: "Puesta a punto de vivienda", en: "Home preparation" },
  redes: { es: "Instalación de redes", en: "Network installation" },
  "reemplazo-ventilador-techo": { es: "Sustitución de ventilador de techo", en: "Ceiling fan replacement" },
  repairs: { es: "Pequeñas reparaciones", en: "Small repairs" },
  "bathroom-accessory-fixing": { es: "Fijación de accesorios de baño", en: "Bathroom accessory fixing" },
  "curtain-rail-adjustments": { es: "Ajuste de rieles de cortina", en: "Curtain rail adjustment" },
  "door-adjustment": { es: "Ajuste de puerta", en: "Door adjustment" },
  "furniture-touch-up-fixes": { es: "Retoques y pequeñas reparaciones de muebles", en: "Furniture touch-ups and minor repairs" },
  "kitchen-minor-fixes": { es: "Pequeñas reparaciones de cocina", en: "Minor kitchen repairs" },
  "minor-wall-fixes": { es: "Pequeñas reparaciones de pared", en: "Minor wall repairs" },
  "mirror-remounting": { es: "Recolocación de espejo", en: "Mirror remounting" },
  "move-out-touch-ups": { es: "Retoques antes de una mudanza", en: "Move-out touch-ups" },
  "multiple-small-repairs": { es: "Varias pequeñas reparaciones", en: "Multiple small repairs" },
  "sealing-gap-filling": { es: "Sellado y relleno de juntas", en: "Gap sealing and filling" },
  "shelf-refixing": { es: "Recolocación de estante", en: "Shelf refixing" },
  "small-drilling-jobs": { es: "Pequeños trabajos de perforación", en: "Small drilling jobs" },
  "socket-cover-straightening": { es: "Ajuste de tapa de enchufe", en: "Socket cover straightening" },
  "wall-anchor-installation": { es: "Instalación de anclajes de pared", en: "Wall anchor installation" },
  "reparacion-agujeros-pared": { es: "Reparación de agujeros en pared", en: "Wall hole repair" },
  "reparacion-paredes": { es: "Reparación de paredes", en: "Wall repair" },
  "reparacion-piso-alquiler": { es: "Reparación de piso de alquiler", en: "Rental flat repairs" },
  "reparaciones-airbnb": { es: "Reparaciones para Airbnb", en: "Airbnb repairs" },
  "reparaciones-antes-entrega-piso": { es: "Reparaciones antes de entregar el piso", en: "Pre-handover flat repairs" },
  "retoques-pintura": { es: "Retoques de pintura", en: "Paint touch-ups" },
  "seguridad-comercial": { es: "Seguridad para comercios", en: "Commercial security" },
  "smart-home": { es: "Hogar inteligente", en: "Smart home" },
  starlink: { es: "Instalación de Starlink", en: "Starlink installation" },
  "tv-mounting": { es: "Instalación de TV", en: "TV mounting" },
  "instalar-soundbar": { es: "Instalación de barra de sonido", en: "Soundbar installation" },
  "ventilador-techo-con-luz": { es: "Ventilador de techo con luz", en: "Ceiling fan with light installation" },
  "tabiques-pladur": { es: "Tabiques de pladur", en: "Drywall partitions" },
  "techo-registrable": { es: "Techo registrable", en: "Suspended access ceiling" },
  "techos-pladur": { es: "Techos de pladur", en: "Drywall ceilings" },
};

export function serviceLabelForPath(path: string, locale: string) {
  const slug = path.split("/").filter(Boolean).at(-1) || "handyman";
  const label = SERVICE_LABELS[slug];
  if (!label) throw new Error(`Missing service label for route: ${path}`);
  return locale === "es" ? label.es : label.en;
}
