export type CatalogService = {
  id: string;
  label: string;
  labelEs: string;
  price: number;
  badge?: string;
  badgeEs?: string;
};

export const SERVICE_CATALOG: Record<string, CatalogService[]> = {
  Handyman: [
    {
      id: "handyman-small-repair",
      label: "Small home repair",
      labelEs: "Pequeña reparación del hogar",
      price: 35,
      badge: "Popular",
      badgeEs: "Popular",
    },
    {
      id: "handyman-assembly",
      label: "Assembly or installation",
      labelEs: "Montaje o instalación",
      price: 49,
    },
    {
      id: "handyman-wall-mounting",
      label: "Hang a shelf, mirror or accessory",
      labelEs: "Colgar estante, espejo o accesorio",
      price: 35,
    },
    {
      id: "handyman-adjustment",
      label: "Door, handle, hinge or furniture adjustment",
      labelEs: "Ajuste de puerta, manilla, bisagra o mueble",
      price: 35,
    },
    {
      id: "handyman-multiple-jobs",
      label: "Multiple small jobs in one visit",
      labelEs: "Varios trabajos pequeños en una visita",
      price: 49,
      badge: "Best value",
      badgeEs: "Mejor opción",
    },
    {
      id: "handyman-inspection",
      label: "Visit and inspection",
      labelEs: "Visita y revisión",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "handyman-custom-job",
      label: "Other handyman job / Send details",
      labelEs: "Otro trabajo handyman / Enviar detalles",
      price: 49,
      badge: "Not listed?",
      badgeEs: "¿No está en la lista?",
    },
  ],
  "TV Mounting": [
    {
      id: "tv-small",
      label: "TV mounting up to 65”",
      labelEs: "Instalación de TV hasta 65”",
      price: 49,
    },
    {
      id: "tv-medium",
      label: "TV mounting from 66”",
      labelEs: "Instalación de TV desde 66”",
      price: 59,
    },
    {
      id: "soundbar",
      label: "Soundbar mounting",
      labelEs: "Instalación de barra de sonido",
      price: 29,
    },
    {
      id: "shelf",
      label: "Media shelf installation",
      labelEs: "Instalación de estante multimedia",
      price: 35,
    },
    {
      id: "raceway",
      label: "Cable concealment with raceway",
      labelEs: "Ocultar cables con canaleta",
      price: 25,
    },
    {
      id: "bracket-install",
      label: "Bracket installation only",
      labelEs: "Solo instalación del soporte",
      price: 35,
    },
    {
      id: "device-behind-tv",
      label: "Your device behind TV",
      labelEs: "Dispositivo detrás del TV",
      price: 29,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "remove-old-tv",
      label: "Remove old TV",
      labelEs: "Retirar TV antiguo",
      price: 19,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  "Ceiling Fans": [
    {
      id: "ceiling-fan-one",
      label: "1 ceiling fan — complete installation",
      labelEs: "1 ventilador — montaje completo",
      price: 45,
    },
    {
      id: "ceiling-fan-two",
      label: "2 ceiling fans — double installation",
      labelEs: "2 ventiladores — instalación doble",
      price: 85,
    },
    {
      id: "ceiling-fan-three",
      label: "3 ceiling fans — pack of 3 units",
      labelEs: "3 ventiladores — pack de 3 unidades",
      price: 125,
    },
    {
      id: "ceiling-fan-from-light",
      label: "Replace a light with a ceiling fan",
      labelEs: "Cambio de lámpara a ventilador",
      price: 45,
    },
    {
      id: "ceiling-fan-replacement",
      label: "Ceiling fan replacement — removal and installation",
      labelEs: "Reemplazo de ventilador — quitamos e instalamos",
      price: 45,
    },
  ],
  Electrical: [
    {
      id: "light-fixture",
      label: "Light fixture installation",
      labelEs: "Instalación de lámpara",
      price: 39,
    },
    {
      id: "ceiling-light",
      label: "Ceiling light installation",
      labelEs: "Instalación de luz de techo",
      price: 45,
    },
    {
      id: "wall-light",
      label: "Wall light / sconce installation",
      labelEs: "Instalación de aplique de pared",
      price: 35,
    },
    {
      id: "switch-replace",
      label: "Switch replacement",
      labelEs: "Cambio de interruptor",
      price: 25,
    },
    {
      id: "socket-replace",
      label: "Socket / outlet replacement",
      labelEs: "Cambio de enchufe / toma",
      price: 29,
    },
    {
      id: "dimmer-install",
      label: "Dimmer installation",
      labelEs: "Instalación de regulador",
      price: 35,
    },
    {
      id: "led-strip",
      label: "LED strip setup",
      labelEs: "Instalación de tira LED",
      price: 35,
    },
    {
      id: "smart-switch",
      label: "Smart switch setup",
      labelEs: "Instalación de interruptor inteligente",
      price: 39,
    },
    {
      id: "light-repair",
      label: "Light repair",
      labelEs: "Reparación de luz",
      price: 29,
    },
    {
      id: "socket-fix",
      label: "Socket repair",
      labelEs: "Reparación de enchufe",
      price: 25,
    },
    {
      id: "cable-fix",
      label: "Visible cable tidy-up",
      labelEs: "Ordenar cables visibles",
      price: 25,
    },
    {
      id: "replace-fixture",
      label: "Replace existing fixture",
      labelEs: "Sustituir lámpara existente",
      price: 35,
    },
    {
      id: "remove-old-light",
      label: "Remove old light",
      labelEs: "Retirar lámpara antigua",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-light",
      label: "Install extra light same visit",
      labelEs: "Instalar luz extra en la misma visita",
      price: 25,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "small-cable-hide",
      label: "Small cable tidy-up",
      labelEs: "Pequeño ordenado de cables",
      price: 15,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  Plumbing: [
    {
      id: "faucet-install",
      label: "Faucet installation",
      labelEs: "Instalación de grifo",
      price: 49,
    },
    {
      id: "sink-fix",
      label: "Sink fitting / visible fix",
      labelEs: "Ajuste de lavabo / reparación visible",
      price: 45,
    },
    {
      id: "toilet-fix",
      label: "Toilet repair / adjustment",
      labelEs: "Reparación / ajuste de inodoro",
      price: 49,
    },
    {
      id: "shower-head",
      label: "Shower head replacement",
      labelEs: "Cambio de alcachofa de ducha",
      price: 29,
    },
    {
      id: "shower-hose",
      label: "Shower hose replacement",
      labelEs: "Cambio de manguera de ducha",
      price: 29,
    },
    {
      id: "valve-replace",
      label: "Valve replacement",
      labelEs: "Cambio de válvula",
      price: 39,
    },
    {
      id: "small-leak",
      label: "Small visible leak fix",
      labelEs: "Reparación de pequeña fuga visible",
      price: 45,
    },
    {
      id: "silicone",
      label: "Silicone renewal",
      labelEs: "Renovación de silicona",
      price: 39,
    },
    {
      id: "trap-fix",
      label: "Sink trap fix",
      labelEs: "Reparación de sifón",
      price: 35,
    },
    {
      id: "drain-check",
      label: "Minor drain check",
      labelEs: "Revisión básica de desagüe",
      price: 29,
    },
    {
      id: "toilet-seat",
      label: "Toilet seat installation",
      labelEs: "Instalación de tapa de inodoro",
      price: 25,
    },
    {
      id: "shower-bracket",
      label: "Shower bracket installation",
      labelEs: "Instalación de soporte de ducha",
      price: 25,
    },
    {
      id: "remove-old-faucet",
      label: "Remove old faucet",
      labelEs: "Retirar grifo antiguo",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "seal-edges",
      label: "Seal edges / finish silicone",
      labelEs: "Sellado / acabado con silicona",
      price: 15,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-adjustment",
      label: "Extra fitting adjustment",
      labelEs: "Ajuste extra de pieza",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  "Furniture Assembly": [
    {
      id: "chair",
      label: "Chair assembly",
      labelEs: "Montaje de silla",
      price: 19,
    },
    {
      id: "desk",
      label: "Desk assembly",
      labelEs: "Montaje de escritorio",
      price: 39,
    },
    {
      id: "bed",
      label: "Bed frame assembly",
      labelEs: "Montaje de cama",
      price: 49,
    },
    {
      id: "wardrobe",
      label: "Wardrobe assembly",
      labelEs: "Montaje de armario",
      price: 79,
    },
    {
      id: "dresser",
      label: "Chest of drawers assembly",
      labelEs: "Montaje de cómoda",
      price: 45,
    },
    {
      id: "shelf-unit",
      label: "Shelving / bookcase assembly",
      labelEs: "Montaje de estantería",
      price: 39,
    },
    {
      id: "tv-stand",
      label: "TV stand / media unit assembly",
      labelEs: "Montaje de mueble TV",
      price: 45,
    },
    {
      id: "wall-fix",
      label: "Furniture wall fixing",
      labelEs: "Fijación de mueble a pared",
      price: 29,
    },
    {
      id: "nightstand",
      label: "Nightstand assembly",
      labelEs: "Montaje de mesita de noche",
      price: 25,
    },
    {
      id: "coffee-table",
      label: "Coffee table assembly",
      labelEs: "Montaje de mesa de centro",
      price: 29,
    },
    {
      id: "dining-table",
      label: "Dining table assembly",
      labelEs: "Montaje de mesa de comedor",
      price: 45,
    },
    {
      id: "cabinet-small",
      label: "Small cabinet assembly",
      labelEs: "Montaje de armario pequeño",
      price: 39,
    },
    {
      id: "remove-packaging",
      label: "Remove packaging",
      labelEs: "Retirar embalaje",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "minor-leveling",
      label: "Minor leveling / adjustment",
      labelEs: "Nivelación / ajuste pequeño",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-anchor",
      label: "Extra anchor to wall",
      labelEs: "Anclaje extra a pared",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  Drywall: [
    {
      id: "drywall-patch-small",
      label: "Small drywall patch",
      labelEs: "Pequeño parche de pladur",
      price: 35,
    },
    {
      id: "drywall-patch-medium",
      label: "Medium drywall patch",
      labelEs: "Parche mediano de pladur",
      price: 49,
    },
    {
      id: "wall-cutout",
      label: "Wall cutout",
      labelEs: "Corte en pared",
      price: 39,
    },
    {
      id: "anchor-hole-repair",
      label: "Anchor hole repair",
      labelEs: "Reparación de agujeros de tacos",
      price: 25,
    },
    {
      id: "crack-repair",
      label: "Crack repair",
      labelEs: "Reparación de grieta",
      price: 29,
    },
    {
      id: "joint-touchup",
      label: "Joint touch-up",
      labelEs: "Retoque de junta",
      price: 29,
    },
    {
      id: "surface-sanding",
      label: "Surface prep / sanding",
      labelEs: "Preparación / lijado",
      price: 25,
    },
    {
      id: "paint-ready",
      label: "Paint-ready finish area",
      labelEs: "Acabado listo para pintar",
      price: 39,
    },
    {
      id: "small-hole-fill",
      label: "Small hole filling",
      labelEs: "Relleno de agujero pequeño",
      price: 19,
    },
    {
      id: "wall-skim",
      label: "Small skim coat area",
      labelEs: "Pequeño alisado de pared",
      price: 35,
    },
    {
      id: "old-anchor-remove",
      label: "Remove old anchors",
      labelEs: "Retirar tacos antiguos",
      price: 19,
    },
    {
      id: "wall-touchup",
      label: "Minor wall touch-up",
      labelEs: "Retoque pequeño de pared",
      price: 25,
    },
    {
      id: "extra-sanding",
      label: "Extra sanding",
      labelEs: "Lijado extra",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "small-repaint",
      label: "Small repaint touch-up",
      labelEs: "Pequeño retoque de pintura",
      price: 15,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "hardware-remove",
      label: "Remove old hardware",
      labelEs: "Retirar herrajes antiguos",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  Repairs: [
    {
      id: "minor-repair-visit",
      label: "Minor repair visit",
      labelEs: "Visita para reparación menor",
      price: 29,
    },
    {
      id: "curtain-adjust",
      label: "Curtain rod adjustment",
      labelEs: "Ajuste de barra de cortina",
      price: 25,
    },
    {
      id: "shelf-refix",
      label: "Shelf re-fix",
      labelEs: "Recolocar estante",
      price: 25,
    },
    {
      id: "handle-repair",
      label: "Loose handle / fitting repair",
      labelEs: "Reparación de manilla / pieza suelta",
      price: 19,
    },
    {
      id: "silicone-fix",
      label: "Silicone / sealing fix",
      labelEs: "Arreglo de silicona / sellado",
      price: 25,
    },
    {
      id: "small-wall-fix",
      label: "Small wall fix",
      labelEs: "Pequeña reparación de pared",
      price: 25,
    },
    {
      id: "mount-correction",
      label: "Mounting correction / re-level",
      labelEs: "Corrección / nivelación",
      price: 29,
    },
    {
      id: "home-adjustment",
      label: "General home adjustment",
      labelEs: "Ajuste general del hogar",
      price: 25,
    },
    {
      id: "drawer-fix",
      label: "Drawer adjustment",
      labelEs: "Ajuste de cajón",
      price: 19,
    },
    {
      id: "door-stop-install",
      label: "Door stop installation",
      labelEs: "Instalación de tope de puerta",
      price: 19,
    },
    {
      id: "loose-fixture-fix",
      label: "Loose fixture fix",
      labelEs: "Arreglo de pieza suelta",
      price: 25,
    },
    {
      id: "small-refit",
      label: "Small re-fit / tighten",
      labelEs: "Pequeño ajuste / apriete",
      price: 19,
    },
    {
      id: "extra-small-fix",
      label: "Extra small fix same visit",
      labelEs: "Arreglo extra pequeño",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "hardware-replace",
      label: "Hardware replacement",
      labelEs: "Cambio de herraje",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "finish-adjustment",
      label: "Re-tightening / finishing",
      labelEs: "Reapriete / acabado",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  "Doors & Hardware": [
    {
      id: "door-handle",
      label: "Door handle replacement",
      labelEs: "Cambio de manilla de puerta",
      price: 25,
    },
    {
      id: "hinge-adjust",
      label: "Hinge adjustment",
      labelEs: "Ajuste de bisagra",
      price: 25,
    },
    {
      id: "lock-replace",
      label: "Lock replacement (basic)",
      labelEs: "Cambio de cerradura básica",
      price: 39,
    },
    {
      id: "closer-adjust",
      label: "Door closer adjustment",
      labelEs: "Ajuste de cierrapuertas",
      price: 29,
    },
    {
      id: "strike-plate",
      label: "Strike plate adjustment",
      labelEs: "Ajuste de cerradero",
      price: 19,
    },
    {
      id: "latch-fix",
      label: "Latch alignment fix",
      labelEs: "Ajuste de pestillo",
      price: 25,
    },
    {
      id: "cabinet-handle",
      label: "Cabinet handle installation",
      labelEs: "Instalación de tirador",
      price: 19,
    },
    {
      id: "door-align",
      label: "Minor door alignment",
      labelEs: "Alineación pequeña de puerta",
      price: 29,
    },
    {
      id: "door-stop",
      label: "Door stop install",
      labelEs: "Instalación de tope de puerta",
      price: 19,
    },
    {
      id: "peephole-install",
      label: "Peephole installation",
      labelEs: "Instalación de mirilla",
      price: 25,
    },
    {
      id: "closet-door-fix",
      label: "Closet door adjustment",
      labelEs: "Ajuste de puerta de armario",
      price: 25,
    },
    {
      id: "small-lock-fix",
      label: "Small lock fix",
      labelEs: "Pequeña reparación de cerradura",
      price: 29,
    },
    {
      id: "remove-old-hardware",
      label: "Remove old hardware",
      labelEs: "Retirar herraje antiguo",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-handle",
      label: "Extra handle same visit",
      labelEs: "Manilla extra",
      price: 8,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "finish-adjust",
      label: "Small finish adjustment",
      labelEs: "Pequeño ajuste final",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  "Smart Home": [
    {
      id: "camera-setup",
      label: "Camera setup",
      labelEs: "Configuración de cámara",
      price: 39,
    },
    {
      id: "doorbell-setup",
      label: "Smart doorbell setup",
      labelEs: "Configuración de timbre inteligente",
      price: 39,
    },
    {
      id: "smart-lock",
      label: "Smart lock installation",
      labelEs: "Instalación de cerradura inteligente",
      price: 49,
    },
    {
      id: "sensor-setup",
      label: "Sensor setup",
      labelEs: "Configuración de sensor",
      price: 25,
    },
    {
      id: "smart-plug",
      label: "Smart plug setup",
      labelEs: "Configuración de enchufe inteligente",
      price: 19,
    },
    {
      id: "smart-switch",
      label: "Smart switch setup",
      labelEs: "Configuración de interruptor inteligente",
      price: 39,
    },
    {
      id: "wifi-device",
      label: "Wi-Fi device setup",
      labelEs: "Configuración de dispositivo Wi-Fi",
      price: 25,
    },
    {
      id: "app-pairing",
      label: "App connection / pairing",
      labelEs: "Conexión con app",
      price: 19,
    },
    {
      id: "indoor-camera",
      label: "Indoor camera install",
      labelEs: "Instalación de cámara interior",
      price: 35,
    },
    {
      id: "outdoor-camera",
      label: "Outdoor camera setup",
      labelEs: "Configuración de cámara exterior",
      price: 49,
    },
    {
      id: "hub-setup",
      label: "Smart hub setup",
      labelEs: "Configuración de hub inteligente",
      price: 35,
    },
    {
      id: "device-reset",
      label: "Smart device reset / reconnect",
      labelEs: "Reset / reconexión de dispositivo",
      price: 25,
    },
    {
      id: "extra-device-pair",
      label: "Extra device pairing",
      labelEs: "Emparejar dispositivo extra",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "smart-cable-tidy",
      label: "Cable tidy-up",
      labelEs: "Ordenar cables",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "remove-old-device",
      label: "Remove old smart device",
      labelEs: "Retirar dispositivo antiguo",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  Kitchen: [
    {
      id: "kitchen-shelf",
      label: "Kitchen shelf install",
      labelEs: "Instalación de estante de cocina",
      price: 35,
    },
    {
      id: "kitchen-rail",
      label: "Kitchen rail install",
      labelEs: "Instalación de barra de cocina",
      price: 29,
    },
    {
      id: "cabinet-handle",
      label: "Cabinet handle installation",
      labelEs: "Instalación de tirador",
      price: 19,
    },
    {
      id: "cabinet-adjust",
      label: "Cabinet door adjustment",
      labelEs: "Ajuste de puerta de mueble",
      price: 25,
    },
    {
      id: "under-light",
      label: "Under-cabinet light install",
      labelEs: "Instalación de luz bajo mueble",
      price: 35,
    },
    {
      id: "backsplash-accessory",
      label: "Kitchen accessory mounting",
      labelEs: "Montaje de accesorio de cocina",
      price: 25,
    },
    {
      id: "dish-rack",
      label: "Dish rack installation",
      labelEs: "Instalación de escurridor",
      price: 25,
    },
    {
      id: "wall-hook",
      label: "Kitchen wall hooks / bar",
      labelEs: "Ganchos / barra de cocina",
      price: 19,
    },
    {
      id: "small-shelf",
      label: "Small spice shelf install",
      labelEs: "Estante pequeño para especias",
      price: 25,
    },
    {
      id: "bin-system",
      label: "Waste bin system install",
      labelEs: "Sistema de cubos de basura",
      price: 29,
    },
    {
      id: "filter-bracket",
      label: "Filter / bracket mounting",
      labelEs: "Montaje de filtro / soporte",
      price: 29,
    },
    {
      id: "kitchen-finish-fix",
      label: "Small kitchen fitting fix",
      labelEs: "Pequeño arreglo de cocina",
      price: 25,
    },
    {
      id: "extra-handle-kitchen",
      label: "Extra handle same visit",
      labelEs: "Tirador extra",
      price: 8,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "remove-old-accessory",
      label: "Remove old accessory",
      labelEs: "Retirar accesorio antiguo",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "small-seal-finish",
      label: "Small seal / finish touch-up",
      labelEs: "Pequeño sellado / acabado",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  Bathroom: [
    {
      id: "mirror-install",
      label: "Mirror installation",
      labelEs: "Instalación de espejo",
      price: 35,
    },
    {
      id: "holder-install",
      label: "Towel / paper holder install",
      labelEs: "Instalación de toallero / portarrollos",
      price: 25,
    },
    {
      id: "bath-cabinet",
      label: "Bathroom cabinet installation",
      labelEs: "Instalación de mueble de baño",
      price: 39,
    },
    {
      id: "shower-shelf",
      label: "Shower shelf install",
      labelEs: "Instalación de estante de ducha",
      price: 25,
    },
    {
      id: "soap-dispenser",
      label: "Soap dispenser mount",
      labelEs: "Montaje de dispensador",
      price: 19,
    },
    {
      id: "toilet-holder",
      label: "Toilet paper holder install",
      labelEs: "Instalación de portarrollos",
      price: 19,
    },
    {
      id: "robe-hook",
      label: "Robe hook installation",
      labelEs: "Instalación de gancho",
      price: 19,
    },
    {
      id: "small-seal",
      label: "Bathroom silicone touch-up",
      labelEs: "Retoque de silicona en baño",
      price: 25,
    },
    {
      id: "bath-light-fix",
      label: "Bathroom light fitting fix",
      labelEs: "Arreglo de luz de baño",
      price: 29,
    },
    {
      id: "glass-shelf",
      label: "Glass shelf installation",
      labelEs: "Instalación de estante de vidrio",
      price: 29,
    },
    {
      id: "mirror-adjust",
      label: "Mirror re-level / adjust",
      labelEs: "Ajuste / nivelación de espejo",
      price: 19,
    },
    {
      id: "bath-accessory-set",
      label: "Bathroom accessory set install",
      labelEs: "Instalación de set de accesorios",
      price: 39,
    },
    {
      id: "remove-old-holder",
      label: "Remove old holder",
      labelEs: "Retirar soporte antiguo",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-accessory",
      label: "Extra accessory same visit",
      labelEs: "Accesorio extra",
      price: 8,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "silicone-finish-bath",
      label: "Finish silicone touch-up",
      labelEs: "Retoque final de silicona",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  "Move-In Setup": [
    {
      id: "curtain-install",
      label: "Curtain installation",
      labelEs: "Instalación de cortinas",
      price: 35,
    },
    {
      id: "blind-install",
      label: "Blind installation",
      labelEs: "Instalación de estor / persiana",
      price: 35,
    },
    {
      id: "shelf-install",
      label: "Shelf installation",
      labelEs: "Instalación de estante",
      price: 29,
    },
    {
      id: "mirror-mount",
      label: "Mirror mounting",
      labelEs: "Montaje de espejo",
      price: 35,
    },
    {
      id: "wall-hook-set",
      label: "Wall hooks / small accessories",
      labelEs: "Ganchos / accesorios pequeños",
      price: 19,
    },
    {
      id: "tv-stand-setup",
      label: "TV stand setup",
      labelEs: "Montaje de mueble TV",
      price: 39,
    },
    {
      id: "bed-setup",
      label: "Bed setup",
      labelEs: "Montaje de cama",
      price: 49,
    },
    {
      id: "desk-setup",
      label: "Desk setup",
      labelEs: "Montaje de escritorio",
      price: 39,
    },
    {
      id: "dresser-setup",
      label: "Dresser setup",
      labelEs: "Montaje de cómoda",
      price: 45,
    },
    {
      id: "basic-room-setup",
      label: "Basic room setup",
      labelEs: "Preparación básica de habitación",
      price: 49,
    },
    {
      id: "entryway-setup",
      label: "Entryway setup",
      labelEs: "Preparación de entrada",
      price: 29,
    },
    {
      id: "movein-essentials",
      label: "Move-in essentials install",
      labelEs: "Instalación de básicos de mudanza",
      price: 49,
    },
    {
      id: "packaging-remove",
      label: "Packaging removal",
      labelEs: "Retirar embalaje",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-small-install",
      label: "Extra small install same visit",
      labelEs: "Instalación extra pequeña",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "layout-adjust",
      label: "Minor layout adjustment",
      labelEs: "Pequeño ajuste de distribución",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
  Exterior: [
    {
      id: "exterior-repair",
      label: "Exterior repair",
      labelEs: "Reparación exterior",
      price: 49,
    },
    {
      id: "fence-repair",
      label: "Fence repair",
      labelEs: "Reparación de valla",
      price: 45,
    },
    {
      id: "outdoor-light",
      label: "Outdoor light install",
      labelEs: "Instalación de luz exterior",
      price: 49,
    },
    {
      id: "house-number",
      label: "House number install",
      labelEs: "Instalación de número de casa",
      price: 19,
    },
    {
      id: "mailbox-mount",
      label: "Mailbox installation",
      labelEs: "Instalación de buzón",
      price: 29,
    },
    {
      id: "doorbell-exterior",
      label: "Exterior doorbell install",
      labelEs: "Instalación de timbre exterior",
      price: 29,
    },
    {
      id: "outdoor-camera",
      label: "Outdoor camera mount",
      labelEs: "Montaje de cámara exterior",
      price: 49,
    },
    {
      id: "wall-hook-outdoor",
      label: "Outdoor wall hook / bracket",
      labelEs: "Gancho / soporte exterior",
      price: 25,
    },
    {
      id: "small-gate-fix",
      label: "Small gate adjustment",
      labelEs: "Pequeño ajuste de puerta exterior",
      price: 35,
    },
    {
      id: "exterior-silicone",
      label: "Exterior sealing touch-up",
      labelEs: "Retoque de sellado exterior",
      price: 29,
    },
    {
      id: "outdoor-accessory",
      label: "Outdoor accessory mount",
      labelEs: "Montaje de accesorio exterior",
      price: 25,
    },
    {
      id: "small-facade-fix",
      label: "Small facade fix",
      labelEs: "Pequeño arreglo de fachada",
      price: 39,
    },
    {
      id: "remove-old-outdoor-item",
      label: "Remove old outdoor item",
      labelEs: "Retirar elemento exterior antiguo",
      price: 10,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "extra-outdoor-fix",
      label: "Extra outdoor fix same visit",
      labelEs: "Arreglo exterior extra",
      price: 15,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "weather-finish",
      label: "Weather finish touch-up",
      labelEs: "Retoque de acabado exterior",
      price: 12,
      badge: "Add-on",
      badgeEs: "Extra",
    },
    {
      id: "inspection",
      label: "Visit & inspection",
      labelEs: "Visita e inspección",
      price: 49,
      badge: "Base",
      badgeEs: "Base",
    },
    {
      id: "custom-job",
      label: "Custom job / Not listed",
      labelEs: "Trabajo personalizado / No está en la lista",
      price: 49,
      badge: "Popular",
      badgeEs: "Popular",
    },
  ],
};

export function getCatalogServices(category: string): CatalogService[] {
  return SERVICE_CATALOG[category] ?? [];
}

function normalizeCatalogText(value: string) {
  return value
    .trim()
    .toLocaleLowerCase()
    .replace(/[”“"']/g, "")
    .replace(/\s+/g, " ");
}

export function findCatalogService(category: string, label: string) {
  const normalized = normalizeCatalogText(label);
  return getCatalogServices(category).find(
    (service) =>
      normalizeCatalogText(service.label) === normalized ||
      normalizeCatalogText(service.labelEs) === normalized,
  );
}
