"use client";

import { useEffect, useMemo, useState } from "react";
import AdminNav from "./AdminNav";

type Metrics = { visitors:number;sessions:number;leads:number;bookings:number;completedJobs:number;bookedRevenue:number;completedRevenue:number;collectedRevenue:number;lostLeads:number;potentialRevenueLost:number;cancelled:number;newCustomers:number;repeatCustomers:number;repeatRevenue:number };
type Row = { category?:string;channel?:string;lang?:string;visitors:number;leads:number;bookings:number;completed?:number;revenue:number };
type TableRow = Row & { landing?: string; device?: string };
type Snapshot = { metrics:Metrics;services:Row[];channels:Row[];locales:Row[];landings:Array<Row&{landing:string}>;devices:Array<Row&{device:string}>;geography:Array<{city:string;area:string;bookings:number;completed:number;revenue:number;aov:number}>;ctas:Array<{cta:string;clicks:number;leads:number;bookings:number;revenue:number}>;promotions:Array<{promo_id:string;views:number;clicks:number;bookings:number;revenue:number}>;funnel:Array<{stage:string;users:number}>;lost:Array<{reason:string;leads:number;potential:number}>;dataQuality:Record<string,number> };
type ResponseData = { current:Snapshot;last7:Snapshot;previous7:Snapshot;days:number;model:"first"|"last" };
const money=(n:number)=>new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n||0);
const pct=(a:number,b:number)=>b?`${((a/b)*100).toFixed(1)}%`:"Insufficient data";
const rev100=(revenue:number,visitors:number)=>visitors?money(revenue/visitors*100):"Insufficient data";

export default function GrowthAnalyticsClient(){
  const [days,setDays]=useState(1),[model,setModel]=useState<"first"|"last">("last"),[data,setData]=useState<ResponseData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true);setError("");void fetch(`/api/admin/growth-analytics?days=${days}&model=${model}`,{cache:"no-store"}).then(async r=>({r,b:await r.json()})).then(({r,b})=>r.ok?setData(b):setError(b.error||"Could not load analytics")).catch(()=>setError("Could not load analytics")).finally(()=>setLoading(false))},[days,model]);
  const m=data?.current.metrics;
  const insights=useMemo(()=>{
    if(!data)return[];const rows:string[]=[];
    data.last7.services.forEach(s=>{if(s.visitors>=20&&s.leads===0)rows.push(`${s.category}: high traffic (${s.visitors}) and zero leads`);if(s.visitors>=10&&s.leads/s.visitors>.08)rows.push(`${s.category}: strong conversion ${pct(s.leads,s.visitors)} — consider more traffic`)});
    const current=pctNumber(data.last7.metrics.leads,data.last7.metrics.visitors),previous=pctNumber(data.previous7.metrics.leads,data.previous7.metrics.visitors);
    if(data.last7.metrics.visitors>=30&&data.previous7.metrics.visitors>=30&&current<previous*.75)rows.push(`Visitor → lead conversion fell from ${previous.toFixed(1)}% to ${current.toFixed(1)}%`);
    return rows.slice(0,6)
  },[data]);
  return <main className="min-h-screen bg-[#f4f4f0] p-3 text-[#111] sm:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><AdminNav/>
    <header className="rounded-[2rem] bg-black p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span className="rounded-full bg-yellow-400 px-3 py-1 text-xs font-black uppercase tracking-widest text-black">Commercial Analytics 2.0</span><h1 className="mt-4 text-3xl font-black sm:text-5xl">Owner dashboard</h1><p className="mt-2 text-sm text-white/60">Visitors → leads → bookings → completed jobs → collected revenue. Unknown attribution stays unknown.</p></div><div className="flex flex-wrap gap-2"><select value={model} onChange={e=>setModel(e.target.value as "first"|"last")} className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-black"><option value="last">Last touch</option><option value="first">First touch</option></select>{[[1,"Today"],[7,"7 days"],[30,"30 days"],[90,"90 days"]].map(([n,label])=><button key={n} onClick={()=>setDays(Number(n))} className={`rounded-xl px-3 py-2 text-sm font-black ${days===n?"bg-yellow-400 text-black":"bg-white/10"}`}>{label}</button>)}</div></div></header>
    {error?<div className="rounded-2xl bg-red-50 p-5 font-bold text-red-700">{error}. Apply the Commercial Analytics 2.0 migration first.</div>:null}{loading?<div className="rounded-2xl bg-white p-8 text-center font-bold">Loading verified commercial data…</div>:null}
    {m?<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
      <Kpi label="Visitors" value={m.visitors}/><Kpi label="Leads" value={m.leads} note={pct(m.leads,m.visitors)+" visitor → lead"}/><Kpi label="Bookings" value={m.bookings} note={pct(m.bookings,m.leads)+" lead → booking"}/><Kpi label="Completed" value={m.completedJobs}/><Kpi label="Booked €" value={money(m.bookedRevenue)} accent/><Kpi label="Completed €" value={money(m.completedRevenue)} accent/><Kpi label="Collected €" value={money(m.collectedRevenue)} accent/><Kpi label="AOV" value={m.completedJobs?money(m.completedRevenue/m.completedJobs):"Insufficient data"}/><Kpi label="Revenue / 100 visitors" value={rev100(m.completedRevenue,m.visitors)}/><Kpi label="Lost leads" value={m.lostLeads}/><Kpi label="Potential lost €" value={money(m.potentialRevenueLost)} warning/><Kpi label="Repeat revenue" value={money(m.repeatRevenue)} note={`${m.repeatCustomers} repeat customers`}/>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.6fr_.8fr]"><Panel title="Service performance" subtitle="Comparable canonical categories across ES and EN"><Table rows={data!.current.services} labelKey="category"/></Panel><Panel title="Calculator funnel" subtitle="Unique sessions; percentages use the previous meaningful stage"><Funnel rows={data!.current.funnel}/></Panel></section>
    <section className="grid gap-5 lg:grid-cols-2"><Panel title="Acquisition channels" subtitle={`${model} attribution; unknown is shown explicitly`}><Table rows={data!.current.channels} labelKey="channel"/></Panel><Panel title="ES vs EN" subtitle="Traffic language is based on session landing; downstream records use normalized locale"><Table rows={data!.current.locales} labelKey="lang"/></Panel></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title="Money pages" subtitle="Landing page traffic and directly attributable downstream revenue"><Table rows={data!.current.landings} labelKey="landing"/></Panel><Panel title="Device performance" subtitle="Mobile, desktop and tablet"><Table rows={data!.current.devices} labelKey="device"/></Panel></section>
    <section className="grid gap-5 xl:grid-cols-3"><Panel title="CTA performance" subtitle="Impressions are omitted where they cannot be measured reliably"><Compact rows={data!.current.ctas.map(x=>({label:x.cta,detail:`${x.clicks} clicks · ${x.leads} leads · ${x.bookings} bookings · ${money(x.revenue)}`}))}/></Panel><Panel title="Geography" subtitle="CRM area, not browser IP geography"><Compact rows={data!.current.geography.map(x=>({label:`${x.city} · ${x.area}`,detail:`${x.bookings} bookings · ${money(x.revenue)} · AOV ${money(x.aov)}`}))}/></Panel><Panel title="Promotions" subtitle="Generic promo IDs; AC €49 is measured end-to-end"><Compact rows={data!.current.promotions.map(x=>({label:x.promo_id,detail:`${x.views} views → ${x.clicks} clicks → ${x.bookings} bookings · ${money(x.revenue)}`}))}/></Panel></section>
    <section className="grid gap-5 lg:grid-cols-3"><Panel title="Opportunities / problems" subtitle="Deterministic rules, minimum sample sizes"><ul className="space-y-3">{insights.length?insights.map(x=><li key={x} className="rounded-xl bg-yellow-50 p-3 text-sm font-bold">{x}</li>):<li className="text-sm text-neutral-500">No reliable alert at the current sample size.</li>}</ul></Panel><Panel title="Lost lead reasons" subtitle="Potential value is not real revenue"><div className="space-y-2">{data!.current.lost.map(x=><div key={x.reason} className="flex justify-between rounded-xl bg-neutral-50 p-3 text-sm"><b>{x.reason}</b><span>{x.leads} · {money(x.potential)}</span></div>)}</div></Panel><Panel title="Data quality" subtitle="Fix these before trusting affected breakdowns"><div className="space-y-2">{Object.entries(data!.current.dataQuality).map(([k,v])=><div key={k} className="flex justify-between rounded-xl bg-neutral-50 p-3 text-sm"><span>{human(k)}</span><b className={v?"text-red-600":"text-green-700"}>{v}</b></div>)}</div></Panel></section>
    </>:null}
  </div></main>
}
const pctNumber=(a:number,b:number)=>b?a/b*100:0;
const human=(s:string)=>s.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase());
function Kpi({label,value,note,accent,warning}:{label:string;value:string|number;note?:string;accent?:boolean;warning?:boolean}){return <article className={`rounded-3xl border p-5 ${accent?"border-yellow-400 bg-yellow-400":warning?"border-red-200 bg-red-50":"border-black/5 bg-white"}`}><p className="text-[11px] font-black uppercase tracking-wider text-black/50">{label}</p><p className="mt-2 text-3xl font-black">{value}</p>{note?<p className="mt-2 text-xs font-semibold text-black/55">{note}</p>:null}</article>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="rounded-[2rem] border border-black/5 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-neutral-500">{subtitle}</p><div className="mt-5 overflow-x-auto">{children}</div></section>}
function Table({rows,labelKey}:{rows:TableRow[];labelKey:"category"|"channel"|"lang"|"landing"|"device"}){return <table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-neutral-400"><th className="py-3">{labelKey}</th><th>Visitors</th><th>Leads</th><th>Bookings</th><th>Completed</th><th>Revenue</th><th>Lead CVR</th><th>Rev/100</th></tr></thead><tbody>{rows.map(r=><tr key={String(r[labelKey])} className="border-b border-black/5"><td className="max-w-[300px] truncate py-3 font-bold">{String(r[labelKey]||"unknown")}</td><td>{r.visitors}</td><td>{r.leads}</td><td>{r.bookings}</td><td>{r.completed??"—"}</td><td>{money(r.revenue)}</td><td>{pct(r.leads,r.visitors)}</td><td>{rev100(r.revenue,r.visitors)}</td></tr>)}</tbody></table>}
function Compact({rows}:{rows:Array<{label:string;detail:string}>}){return <div className="space-y-2">{rows.length?rows.slice(0,12).map(x=><div key={x.label} className="rounded-xl bg-neutral-50 p-3"><b className="block truncate text-sm">{x.label}</b><span className="mt-1 block text-xs text-neutral-500">{x.detail}</span></div>):<p className="text-sm text-neutral-500">Insufficient attribution/data.</p>}</div>}
function Funnel({rows}:{rows:Array<{stage:string;users:number}>}){const first=rows[0]?.users||0;return <div className="space-y-3">{rows.map((r,i)=>{const prev=i?rows[i-1].users:first;return <div key={r.stage}><div className="flex justify-between text-xs font-bold"><span>{human(r.stage)}</span><span>{r.users} · {i?pct(r.users,prev):"100%"}</span></div><div className="mt-1 h-2 rounded-full bg-neutral-100"><div className="h-2 rounded-full bg-yellow-400" style={{width:`${first?Math.max(r.users?3:0,r.users/first*100):0}%`}}/></div></div>})}</div>}
